### ISSUE TITLE
Add keywords for C109s

### ISSUE THREAD

**Issue by sergei-kalugin** [MADStudioNU/the-pulter-project#1010]
https://docs.google.com/spreadsheets/d/1zv-dZ8TMdGD13u66NhCAqDNIvcUKtS8XfPKfbE4Ulvw/edit?gid=1863055128#gid=1863055128&range=K251:K253

- [x] _Dualist and Materialist Theories of Resurrection_
- [x] _Visualizing Monist and Dualist Theories of Resurrection_
- [x] _Sources of “The Brahman”_

**Comment by wendywall** [comment]
> https://docs.google.com/spreadsheets/d/1zv-dZ8TMdGD13u66NhCAqDNIvcUKtS8XfPKfbE4Ulvw/edit?gid=1863055128#gid=1863055128&range=K251:K253
> 
> * [ ]  _Dualist and Materialist Theories of Resurrection_
> * [ ]  _Visualizing Monist and Dualist Theories of Resurrection_
> * [ ]  _Sources of “The Brahman”_

DONE @sergei-kalugin
