### ISSUE TITLE
Add keywords for “Shades of Death: Hester Pulter and Mortality” Exploration

### ISSUE THREAD

**Issue by sergei-kalugin** [MADStudioNU/the-pulter-project#1013]
https://docs.google.com/spreadsheets/d/1zv-dZ8TMdGD13u66NhCAqDNIvcUKtS8XfPKfbE4Ulvw/edit?gid=989390021#gid=989390021&range=H13

**Comment by wendywall** [comment]
Done!



From: Sergei Kalugin ***@***.***>
Date: Thursday, September 26, 2024 at 2:09 PM
To: MADStudioNU/the-pulter-project ***@***.***>
Cc: Wendy L Wall ***@***.***>, Assign ***@***.***>
Subject: Re: [MADStudioNU/the-pulter-project] Add keywords for “Shades of Death: Hester Pulter and Mortality” Exploration (Issue #1013)

Assigned #1013<https://urldefense.com/v3/__https:/github.com/MADStudioNU/the-pulter-project/issues/1013__;!!Dq0X2DkFhyF93HkjWTBQKhk!VlQXrqD_3clVyUMw7IJ4UIrCGc2O_BGaiUGnhMNLQvMQEVX5l-35JZAmcz8n7sYRR8XRV0h7VD3frfnuaifloHXq1uzgTy8$> to @wendywall<https://urldefense.com/v3/__https:/github.com/wendywall__;!!Dq0X2DkFhyF93HkjWTBQKhk!VlQXrqD_3clVyUMw7IJ4UIrCGc2O_BGaiUGnhMNLQvMQEVX5l-35JZAmcz8n7sYRR8XRV0h7VD3frfnuaifloHXqEzA9aB4$>.
