### ISSUE TITLE
Exploration Shades of death: Update preview

### ISSUE THREAD

**Issue by lhn4977** [MADStudioNU/the-pulter-project#1015]

**Comment by sergei-kalugin** [comment]
This should have been updated automatically. If you don't see the changes in the browser, a hard reload of the page might be needed to reset the cached version.

<img width="753" alt="Screenshot 2024-09-30 at 9 22 58 AM" src="https://github.com/user-attachments/assets/097ab93e-ab61-4873-bd51-905e158ef5f9">
