### ISSUE TITLE
Corrections to Poem 4 (Elemental and Transcription)

### ISSUE THREAD

**Issue by emmacohen-nu** [MADStudioNU/the-pulter-project#1022]
@sergei-kalugin 
Linking the correction sheet for Poem 4 here:
https://docs.google.com/spreadsheets/d/1rpHzI0-KlAGDsTgLnQ4ZT96Q2hkc_tGhiuIz84SVsP0/edit?usp=sharing

**Comment by lhn4977** [comment]
@emmacohen-nu https://pulterproject-preview-c7ga82m1pzxmbn.netlify.app/poems/vm/the-complaint-of-thames-1647/

please check carefully and if there are still any corrections needed then please create a new issue and assign me. otherwise I'll publish these changes to the site soon
