### ISSUE TITLE
Publish A112 and C112s

### ISSUE THREAD

**Issue by lhn4977** [MADStudioNU/the-pulter-project#1050]

**Comment by lhn4977** [comment]
@sergei-kalugin tried publishing, but even though I could merge develop and master, I couldn't publish directly to "master" (to change curation status from "off" to "on") because it's a protected branch. please help publish A112 and C112s, thank you!!

**Comment by sergei-kalugin** [comment]
https://pulterproject.northwestern.edu/poems/ae/the-turtle-and-his-paramour-emblem-47
