### ISSUE TITLE
Push C69 to preview

### ISSUE THREAD

**Issue by lhn4977** [MADStudioNU/the-pulter-project#1053]
At my wit's end here. @sergei-kalugin do you have any idea what I did wrong such that I couldn't deploy C69 to development?

**Comment by sergei-kalugin** [comment]
<img width="518" alt="Screenshot 2024-10-31 at 4 16 08 PM" src="https://github.com/user-attachments/assets/89741e5d-b712-4507-b6a3-f16851139f5b">

There was an error in the markup. Fixed and the new (yet blank) curation is published to the preview.

https://pulterproject-preview-c7ga82m1pzxmbn.netlify.app/poems/ae/heliotropians-emblem-3/#0
