### ISSUE TITLE
Correction to P056 Question

### ISSUE THREAD

**Issue by emmacohen-nu** [MADStudioNU/the-pulter-project#1060]
Hi @sergei-kalugin, while reading P056 for corrections there was a question about whether some formatting that exists for the Transcription of the poem could be applied to the EA. I'm including the correction sheet with screenshots below--does this seem like something that would be possible? Thanks! 

[https://docs.google.com/spreadsheets/d/1gnFcac7kzS3wldVaZSH303tEYXVBNtr4YKk-boVD2qc/edit?usp=sharing](url)

**Comment by lhn4977** [comment]
Chiming in here to say, @emmacohen-nu, that it is possible. If desired, we can change the EE and AE to have the speakers appear in the margin (similar to [Poem 12](https://pulterproject.northwestern.edu/poems/ae/the-garden-or-the-contention-of-flowers/#ae)). Is that what you want? Also note that right now EE and AE show to different ways of marking speakers.

**Comment by emmacohen-nu** [comment]
Thanks @lhn4977! I do think that would more accurately reflect what's in the doc. @wendywall do you want to confirm that the marginal speaker labels would be preferred for EE and AE?

**Comment by wendywall** [comment]
Yes, I think so, if possible to do without tremendous frustration.

Wendy

From: emmacohen-nu ***@***.***>
Date: Thursday, December 12, 2024 at 6:19 PM
To: MADStudioNU/the-pulter-project ***@***.***>
Cc: Wendy L Wall ***@***.***>, Mention ***@***.***>
Subject: Re: [MADStudioNU/the-pulter-project] Correction to P056 Question (Issue #1060)

Thanks @lhn4977<https://urldefense.com/v3/__https:/github.com/lhn4977__;!!Dq0X2DkFhyF93HkjWTBQKhk!VeWmLjjITUSsfL6Gj7yTRIwxn7kvAItXVRDerbX5wRWgvelu4nDM0qYP96vEptmhiTNPWhyNInlUAwD8dYfMK1ikLwXr7qU$>! I do think that would more accurately reflect what's in the doc. @wendywall<https://urldefense.com/v3/__https:/github.com/wendywall__;!!Dq0X2DkFhyF93HkjWTBQKhk!VeWmLjjITUSsfL6Gj7yTRIwxn7kvAItXVRDerbX5wRWgvelu4nDM0qYP96vEptmhiTNPWhyNInlUAwD8dYfMK1ikKqLDDR8$> do you want to confirm that the marginal speaker labels would be preferred for EE and AE?

**Comment by lhn4977** [comment]
https://pulterproject.northwestern.edu/poems/ee/a-dialogue-between-two-sisters-virgins-bewailing-their-solitary-life/ big thanks to @sergei-kalugin !
