### ISSUE TITLE
Troubleshoot issues with P056 left-gutter

### ISSUE THREAD

**Issue by lhn4977** [MADStudioNU/the-pulter-project#1063]
I tried to replicate Poem 12 left-gutter so we can have the speakers on the left margin, but there's some issues in building the site. Would appreciate your help troubleshooting [this commit](https://github.com/MADStudioNU/the-pulter-project/commit/c85f6fd27bd59d3c9ab30e6c43f425d3f78209bd). Thanks @sergei-kalugin !

**Comment by sergei-kalugin** [comment]
Got it. Will take a look at this asap. Thank you!
