### ISSUE TITLE
Poem 74: publish AE after approval

### ISSUE THREAD

**Issue by LeahKnight** [MADStudioNU/the-pulter-project#234]

**Comment by LeahKnight** [comment]
Hi Sergei: I'm not sure why this request to launch Poem 74 was closed on July 22; we'd still like to launch the AE (which is not up). Perhaps you closed it because you saw that the T&EE were already up; I should have specified which bit I meant! Thanks, Leah

**Comment by sergei-kalugin** [comment]
As far as I can tell, A074 was never in preview. Move to preview first?

**Comment by sergei-kalugin** [comment]
Also, the TEi of P074 is missing the editor's name and the editorial note.

**Comment by sergei-kalugin** [comment]
Moved to preview: https://pulterproject-dev-4slasb7dfnyuier8z7y2.netlify.com/poems/ae/the-turtle-emblem-8/

**Comment by LeahKnight** [comment]
Once Sarah and Millie have proofed and we've corrected, we'll publish.
