### ISSUE TITLE
Move "Hester Pulter's Marriage" exploration to preview

### ISSUE THREAD

**Issue by sergei-kalugin** [MADStudioNU/the-pulter-project#298]

**Comment by k-poland** [comment]
Exploration updated; could we push the changes?

**Comment by LeahKnight** [comment]
Once these last changes (re moving the note) are up, this can be published.

**Comment by sergei-kalugin** [comment]
The exploration is live:

https://pulterproject.northwestern.edu/#hester-pulters-marriage
