### ISSUE TITLE
Add Andrea Crow's profile link?

### ISSUE THREAD

**Issue by sergei-kalugin** [MADStudioNU/the-pulter-project#328]
@LeahKnight: is Andrea interested in providing a link to her online profile? This concerns poems 27, 28, and 33.

**Comment by LeahKnight** [comment]
Yes, please! https://www.bc.edu/bc-web/schools/mcas/departments/english/people/faculty-directory/crow--andrea.html

**Comment by sergei-kalugin** [comment]
Done.
