### ISSUE TITLE
Poem 69: fix errors and move to preview

### ISSUE THREAD

**Issue by LeahKnight** [MADStudioNU/the-pulter-project#332]

**Comment by sergei-kalugin** [comment]
Markup does not validate at the moment.

**Comment by LeahKnight** [comment]
Oh - bummer! This was Katrina's first attempt; Katie checked it and thought it look good. Is there anything they/we need to do on this, Sergei?

**Comment by sergei-kalugin** [comment]
I'll look into this really quickly.

**Comment by sergei-kalugin** [comment]
https://pulterproject-dev-4slasb7dfnyuier8z7y2.netlify.com/poems/ee/heliotropians-emblem-3/
