### ISSUE TITLE
Poem 74: publish AE

### ISSUE THREAD

**Issue by katgaro** [MADStudioNU/the-pulter-project#336]

**Comment by sergei-kalugin** [comment]
Published: https://pulterproject.northwestern.edu/poems/ae/the-turtle-emblem-8/

**Comment by sergei-kalugin** [comment]
@LeahKnight, I forgot: did we ask Millie for her profile web link already?

**Comment by LeahKnight** [comment]
@sergei-kalugin, I believe we did, but b/c she's an undergraduate, she doesn't have one.

**Comment by sergei-kalugin** [comment]
Got you
