### ISSUE TITLE
C104 Cetacean Relations: move to preview

### ISSUE THREAD

**Issue by sergei-kalugin** [MADStudioNU/the-pulter-project#338]

**Comment by LeahKnight** [comment]
I'm waiting to hear back from Wendy, but I think we got ahead of ourselves with this one: i.e., I think it needs a review first, so no need to move it to preview yet; it might undergo some changes before that.

**Comment by k-poland** [comment]
Review is done, no changes necessary. Looks like this is okay to push!

**Comment by sergei-kalugin** [comment]
So, @LeahKnight & @k-poland, "moving to preview" or "publishing live?"

**Comment by k-poland** [comment]
Preview, please—we haven’t done a corrections sheet for the encoding yet.

**Comment by sergei-kalugin** [comment]
https://pulterproject-dev-4slasb7dfnyuier8z7y2.netlify.com/poems/ee/the-dolphin-emblem-39/#cetacean-relations
