### ISSUE TITLE
Poem 76: move to preview

### ISSUE THREAD

**Issue by katgaro** [MADStudioNU/the-pulter-project#345]

**Comment by LeahKnight** [comment]
@k-poland Katie, is this something you're able to do, or do I need to ping Sergei?

**Comment by LeahKnight** [comment]
@sergei-kalugin Hi Sergei: would you please move Poem 76 and its Curations back into preview? There was a glitch earlier, but Katrina believes she fixed it. Thanks!

**Comment by sergei-kalugin** [comment]
https://pulterproject-dev-4slasb7dfnyuier8z7y2.netlify.app/poems/ee/wisest-creatures-emblem-10/
