### ISSUE TITLE
Add poster to Poem 76; then publish Poem 76 AE and Curations

### ISSUE THREAD

**Issue by LeahKnight** [MADStudioNU/the-pulter-project#348]
"C076 Mother & Baby POSTER.jpg" in usual folder

**Comment by sergei-kalugin** [comment]
@LeahKnight: may I ask you to revise the metadata for the poster image of Poem 76? I have a slight suspicion that the table rows got shifted somehow and we have a mismatch (or multiple mismatches). The problem can also be in the naming of the files in the poster folder on Drive.

Poster folder: https://drive.google.com/drive/u/0/folders/1X5UaRMIxBE3igzj4eDmgTVgaV-rQGqrA

Poster attribution cell for Poem 76: https://docs.google.com/spreadsheets/d/1zv-dZ8TMdGD13u66NhCAqDNIvcUKtS8XfPKfbE4Ulvw/edit#gid=2031311056&range=M80

**Comment by LeahKnight** [comment]
Oh boy. It looks like a LOT of the posters are mismatched to the poems. I've tried to make some quick adjustments, but I think this will require a thorough comb-through. I'll assign it to @katgaro , that lucky duck. Thanks, Sergei, for flagging this.

**Comment by sergei-kalugin** [comment]
I moved the aforementioned problem here: #363.

**Comment by sergei-kalugin** [comment]
@LeahKnight @wendywall: the poster is ready for your approval:

**Comment by LeahKnight** [comment]
@sergei-kalugin: Approved, thanks!

**Comment by sergei-kalugin** [comment]
(@wendywall @LeahKnight @k-poland @katgaro) ...and we're live:

https://pulterproject.northwestern.edu/poems/ee/wisest-creatures-emblem-10/

**Comment by wendywall** [comment]
Great – thanks!
Wendy

Wendy Wall
Co-director with Leah Knight
The Pulter Project: Poet in the Making<http://pulterproject.northwestern.edu/>
(Follow: @PulterProject)

Director, Kaplan Institute for the Humanities
Avalon Foundation Professor of the Humanities
Charles Deering McCormick Professor of Teaching Excellence
