### ISSUE TITLE
Create new icons for Curations

### ISSUE THREAD

**Issue by sergei-kalugin** [MADStudioNU/the-pulter-project#35]

**Comment by sergei-kalugin** [comment]
@LeahKnight, @syreeves: maybe this is a good time to revisit this.

**Comment by syreeves** [comment]
@sergei-kalugin are there preferred dimensions for the icons?

**Comment by sergei-kalugin** [comment]
No preferred dimensions since it's a vector file, but the aspect ratio is 2:3 right now. Do you have anything in mind? Feel free to share here!

**Comment by syreeves** [comment]
![icon pack](https://user-images.githubusercontent.com/80483087/120671745-aee34800-c45f-11eb-99c5-f268a9731060.jpg)

These are the icon designs Leah and I have gone over. They are just sketches, so nothing has been refined or vectorized yet. I will have to make the lines thicker in both the Manuscript and Curations icons, as they will likely be too small/detailed to look right on a small scale on the website.

**Comment by sergei-kalugin** [comment]
Nice! Yes, you're absolutely right about looking right when shrunk down to 15-20px wide.

**Comment by sergei-kalugin** [comment]
An update from @syreeves:

https://urldefense.com/v3/__https://drive.google.com/drive/u/0/folders/1iJTLunThOWHsq9jRj6mbdH1oVRf4cb3X__;!!Dq0X2DkFhyF93HkjWTBQKhk!BRIDK0NH07N3WIaOCTPPcZ5VFREHneWmU03Dq_sAAe0WGrnsR_q1Wx9ESBNp7_Lx9Z3XigRaGTc$
