### ISSUE TITLE
C17 "Circles and Labyrinths": Add pp-poem Reference?

### ISSUE THREAD

**Issue by sergei-kalugin** [MADStudioNU/the-pulter-project#352]

**Comment by sergei-kalugin** [comment]
The reference to 'The Circle [2]' should be formatted appropriately unless it's a typo (a reference to self, The Circle [1]?)

**Comment by LeahKnight** [comment]
Do you mean that the single quotation marks should be double, @sergei-kalugin? Or something else? (I've asked @katgaro to amend the quotation marks in this and the other Curations for Poem 17 by ESB.)

**Comment by LeahKnight** [comment]
@sergei-kalugin Please pull the Curation “Circles and Labyrinths” from Poem 17; it does not belong there after all.

**Comment by sergei-kalugin** [comment]
Gone
