### ISSUE TITLE
A023: publish

### ISSUE THREAD

**Issue by LeahKnight** [MADStudioNU/the-pulter-project#355]

**Comment by sergei-kalugin** [comment]
@wendywall: A023 has been published and the issue is now closed

https://pulterproject.northwestern.edu/poems/ae/to-astraea/

**Comment by wendywall** [comment]
Great – thanks!

Wendy


Wendy Wall
Co-director with Leah Knight
The Pulter Project: Poet in the Making<http://pulterproject.northwestern.edu/>
(Follow: @PulterProject)

Director, Kaplan Institute for the Humanities
Avalon Foundation Professor of the Humanities
Charles Deering McCormick Professor of Teaching Excellence
