### ISSUE TITLE
Poem 7: Publish Curations by Dolan

### ISSUE THREAD

**Issue by LeahKnight** [MADStudioNU/the-pulter-project#358]

**Comment by sergei-kalugin** [comment]
Six curations for Poem 7 have been published.

https://pulterproject.northwestern.edu/poems/ee/on-those-two-unparalleled-friends-sir-george-lisle-and-sir-charles-lucas-who-were-shot-to-death-at-colchester/#ctxs

@wendywall: FYI above

**Comment by wendywall** [comment]
Thanks so much, Sergei!

Wendy

Wendy Wall
Co-director with Leah Knight
The Pulter Project: Poet in the Making<http://pulterproject.northwestern.edu/>
(Follow: @PulterProject)

Director, Kaplan Institute for the Humanities
Avalon Foundation Professor of the Humanities
Charles Deering McCormick Professor of Teaching Excellence
