### ISSUE TITLE
Poem 104: Publish AE and "Cetacean Relations" Curation

### ISSUE THREAD

**Issue by LeahKnight** [MADStudioNU/the-pulter-project#361]

**Comment by sergei-kalugin** [comment]
**A104**
https://pulterproject.northwestern.edu/poems/ae/the-dolphin-emblem-39/

**C104**
https://pulterproject.northwestern.edu/poems/ae/the-dolphin-emblem-39/#cetacean-relations

@wendywall : FYI above

**Comment by wendywall** [comment]
Thanks so much, Sergei! I let the editor and tweeter know.

Wendy


Wendy Wall
Co-director with Leah Knight
The Pulter Project: Poet in the Making<http://pulterproject.northwestern.edu/>
(Follow: @PulterProject)

Director, Kaplan Institute for the Humanities
Avalon Foundation Professor of the Humanities
Charles Deering McCormick Professor of Teaching Excellence
