### ISSUE TITLE
Add bio link for Kenneth Graham

### ISSUE THREAD

**Issue by sergei-kalugin** [MADStudioNU/the-pulter-project#368]
Would Kenneth like to provide a link to his web profile?

**Comment by wendywall** [comment]
We will check with him.
Wendy

Wendy Wall
Co-director with Leah Knight
The Pulter Project: Poet in the Making<http://pulterproject.northwestern.edu/>
(Follow: @PulterProject)

Director, Kaplan Institute for the Humanities
Avalon Foundation Professor of the Humanities
Charles Deering McCormick Professor of Teaching Excellence

**Comment by LeahKnight** [comment]
https://uwaterloo.ca/english/people-profiles/kenneth-graham
