### ISSUE TITLE
A037 and Curations: fix em/en dashes and re-publish

### ISSUE THREAD

**Issue by katgaro** [MADStudioNU/the-pulter-project#369]

**Comment by sergei-kalugin** [comment]
@wendywall, @LeahKnight: A037 + 2 curations are live:

https://pulterproject.northwestern.edu/poems/ae/aurora-2/

**Comment by wendywall** [comment]
Thanks!
Wendy


Wendy Wall
Co-director with Leah Knight
The Pulter Project: Poet in the Making<http://pulterproject.northwestern.edu/>
(Follow: @PulterProject)

Director, Kaplan Institute for the Humanities
Avalon Foundation Professor of the Humanities
Charles Deering McCormick Professor of Teaching Excellence

**Comment by sergei-kalugin** [comment]
I’ll be applying some formatting related fixes to this later today.
