### ISSUE TITLE
Poem 72: Fix link to poster

### ISSUE THREAD

**Issue by LeahKnight** [MADStudioNU/the-pulter-project#372]
@sergei-kalugin The current URL in the attribution statement is wrong. Please use this one: 
https://www.rijksmuseum.nl/nl/zoeken/objecten?q=charlatans&p=2&ps=12&st=Objects&ii=2#/RP-P-1896-A-19368-1019,14

**Comment by sergei-kalugin** [comment]
Got you, will fix. FYI: everything from the Rijks needs to be referred by a _handle.net_ URL as opposed to what appears in your browser's address bar.

http://hdl.handle.net/10934/RM0001.collect.41496
