### ISSUE TITLE
Poem 78: move EE+T to preview

### ISSUE THREAD

**Issue by sergei-kalugin** [MADStudioNU/the-pulter-project#376]

**Comment by sergei-kalugin** [comment]
@LeahKnight, @wendywall: moving EE+T of Poem 78 to preview?

Also: I created a label ("new label") to mark the newly added content, so we know what needs to be moved around.

**Comment by LeahKnight** [comment]
Thanks, Sergei!

@katgaro is Poem 78's T&EE ready to move to preview?

**Comment by katgaro** [comment]
Yes! 78 T and EE are ready to move to preview.

**Comment by sergei-kalugin** [comment]
@wendywall, @LeahKnight 

https://pulterproject-dev-4slasb7dfnyuier8z7y2.netlify.app/poems/ee/this-vast-leviathan-emblem-12/
