### ISSUE TITLE
Poem 99: capitalize words in the index title

### ISSUE THREAD

**Issue by sergei-kalugin** [MADStudioNU/the-pulter-project#389]
<img width="1022" alt="Screenshot 2020-06-11 12 37 06" src="https://user-images.githubusercontent.com/2558705/84420962-77411780-abe0-11ea-8235-1edbd52899c3.png">

**Comment by wendywall** [comment]
No, this is correct ("but" and "those" are not capitalized).

**Comment by wendywall** [comment]
I stand corrected. Can you make the index page capitalized to match poem title: Mark But Those Hogs.
