### ISSUE TITLE
Poem 116: Publish T&EE (but *not* AE: needs proofing by editors)

### ISSUE THREAD

**Issue by LeahKnight** [MADStudioNU/the-pulter-project#399]
@sergei-kalugin I don't know if it's possible to publish just the T&EE when the AE is also encoded, Sergei; if not, this issue can have a 'not yet' label, with publication delayed until the editors proofread their AE.

**Comment by sergei-kalugin** [comment]
Yes, it is possible, Leah.

**Comment by sergei-kalugin** [comment]
#344 needs to be resolved as well before publishing

**Comment by sergei-kalugin** [comment]
Ok, #344 does not need to be resolved per @LeahKnight ‘s comment.

**Comment by sergei-kalugin** [comment]
@LeahKnight @wendywall 
https://pulterproject.northwestern.edu/poems/ee/british-brennus-emblem-51/
