### ISSUE TITLE
Grant Wendy access to Google Analytics data

### ISSUE THREAD

**Issue by sergei-kalugin** [MADStudioNU/the-pulter-project#400]

**Comment by sergei-kalugin** [comment]
@wendywall: you should have received an email confirming that you now have access to the analytics data for TPP;

@LeahKnight: you're already enrolled.

**Comment by wendywall** [comment]
How do I see it then?

**Comment by sergei-kalugin** [comment]
Does the email have any links or say anything about how to get to the analytics dashboard?

The main page of this service is here: https://analytics.google.com.
