### ISSUE TITLE
Whitney Sperrazza: add bio link

### ISSUE THREAD

**Issue by sergei-kalugin** [MADStudioNU/the-pulter-project#403]
Great to see another exciting collaborator ([AE118](https://pulterproject-dev-4slasb7dfnyuier8z7y2.netlify.app/poems/ae/the-snail-the-tulip-and-the-bee-emblem-53/))! Should we inquire about Whitney's preference in terms of having a link to the professional page? 

Also, TPP's  "About" should also be updated when this goes live.

**Comment by LeahKnight** [comment]
LK asked Whitney Jun.16/20

**Comment by LeahKnight** [comment]
Please use this link for Whitney's bio: https://www.rit.edu/directory/wssgla-whitney-sperrazza
@sergei-kalugin
