### ISSUE TITLE
Poem 83: publish T&EE (once poster up)

### ISSUE THREAD

**Issue by LeahKnight** [MADStudioNU/the-pulter-project#407]

**Comment by sergei-kalugin** [comment]
@LeahKnight @wendywall 

https://pulterproject.northwestern.edu/poems/ee/the-piper-of-hamelin-emblem-17/

**Comment by wendywall** [comment]
Wow – this one is beautiful!
W.


Wendy Wall
Co-director with Leah Knight
The Pulter Project: Poet in the Making<http://pulterproject.northwestern.edu/>
(Follow: @PulterProject)
Avalon Foundation Professor of the Humanities
Northwestern University
