### ISSUE TITLE
Poem 78: publish T&EE once poster added

### ISSUE THREAD

**Issue by LeahKnight** [MADStudioNU/the-pulter-project#408]

**Comment by wendywall** [comment]
Can I remove the "not yet" now?

**Comment by sergei-kalugin** [comment]
Done.

**Comment by sergei-kalugin** [comment]
@wendywall @LeahKnight: this has been published to the world

https://pulterproject.northwestern.edu/poems/ee/this-vast-leviathan-emblem-12/

![Screen Shot 2020-08-12 at 10 54 12 AM](https://user-images.githubusercontent.com/2558705/90037781-34f09100-dc8a-11ea-9574-ccd19ff87956.png)
