### ISSUE TITLE
Poem 95: publish T&EE after poster added

### ISSUE THREAD

**Issue by LeahKnight** [MADStudioNU/the-pulter-project#409]

**Comment by wendywall** [comment]
Can I remove the "not yet" now?

**Comment by sergei-kalugin** [comment]
Yes, I'll do it.

**Comment by sergei-kalugin** [comment]
@LeahKnight @wendywall 

This is published: https://pulterproject.northwestern.edu/poems/ee/this-ugly-sow-emblem-30/
