### ISSUE TITLE
Poem notes not rendering subscript and strikethrough

### ISSUE THREAD

**Issue by k-poland** [MADStudioNU/the-pulter-project#411]
From the corrections sheet for 118 AE: 
l.19, note on "curious," super/subscript and strikethrough do not appear on AE view, but do appear in comparison view 
l.31, note on "did," super/subscript and strikethrough do not appear on AE view, but do appear in comparison view 
Weirdly, superscript appears just fine for me; sub and del don't.

**Comment by LeahKnight** [comment]
@sergei-kalugin  pls. see my email of Jul. 9 for a follow-up query.

**Comment by sergei-kalugin** [comment]
@wendywall @LeahKnight @k-poland: I just want to make sure this is fixed properly and that the encoding is correct.

The note on "curious" in line n. 19:

![Screen Shot 2020-08-12 at 3 23 10 PM](https://user-images.githubusercontent.com/2558705/90064024-cb837900-dcaf-11ea-851b-94df85a8c817.png)

contains word "curious" surrounded with two forward slashes: one in subscript and one in superscript, correct? What is the meaning of the position of the slashes?

**Comment by LeahKnight** [comment]
@sergei-kalugin Those are marks that are typical of the hand we call "probably Pulter's" when it is correcting a poem by adding a word. The insertion is often marked, as here, with a slash below the line, before and a slash following the inserted word.

**Comment by sergei-kalugin** [comment]
@LeahKnight @wendywall OK, does this work?

![Screen Shot 2020-08-12 at 3 51 11 PM](https://user-images.githubusercontent.com/2558705/90066720-b7da1180-dcb3-11ea-8c1b-4036ed9959ed.png)


![Screen Shot 2020-08-12 at 3 51 17 PM](https://user-images.githubusercontent.com/2558705/90066715-b7da1180-dcb3-11ea-909f-e7857d310216.png)

https://pulterproject-dev-4slasb7dfnyuier8z7y2.netlify.app/poems/ae/the-snail-the-tulip-and-the-bee-emblem-53/
