### ISSUE TITLE
Poem 68: re-publish AE

### ISSUE THREAD

**Issue by sergei-kalugin** [MADStudioNU/the-pulter-project#421]

**Comment by sergei-kalugin** [comment]
https://pulterproject-dev-4slasb7dfnyuier8z7y2.netlify.app/poems/vm/come-my-dear-children-emblem-2/

**Comment by wendywall** [comment]
republish when Matt says that the margins are fixed

**Comment by wendywall** [comment]
Leah and I have okayed the preview Matt sent -- looks great to us!

**Comment by LeahKnight** [comment]
@emwitty

**Comment by LeahKnight** [comment]
Yes, please publish, @sergei-kalugin

**Comment by LeahKnight** [comment]
Sorry, guys: I just realized that Sarah and Millie haven't yet proofread their AE.

**Comment by sergei-kalugin** [comment]
But this is only about T+EE. Are we still waiting? Maybe "not yet" tag instead closing?

**Comment by sergei-kalugin** [comment]
Nevermind, I'm looking at the wrong issue, my bad.

**Comment by LeahKnight** [comment]
@sergei-kalugin Poem 68's AE is ready to publish now!

**Comment by sergei-kalugin** [comment]
https://pulterproject.northwestern.edu/poems/ae/come-my-dear-children-emblem-2/
