### ISSUE TITLE
Poem 106: Publish T&EE

### ISSUE THREAD

**Issue by k-poland** [MADStudioNU/the-pulter-project#427]

**Comment by sergei-kalugin** [comment]
There are a few formatting issues I'm seeing:
- em dash after "Which they retaliate in age and need"
- em dash before "a shocking claim" in the headnote

Maybe there's more, I didn't check everything.

**Comment by k-poland** [comment]
Apologies; I don’t seem very good at catching the dashes! I’ve replaced those hyphens with an em dash, and gone through all the other dash-like characters.

**Comment by sergei-kalugin** [comment]
@wendywall @LeahKnight @k-poland 

Published!

https://pulterproject.northwestern.edu/poems/ee/the-ostrich-emblem-41/
