### ISSUE TITLE
Poem 107: Publish T&EE

### ISSUE THREAD

**Issue by k-poland** [MADStudioNU/the-pulter-project#428]

**Comment by sergei-kalugin** [comment]
@LeahKnight 

Before publishing, we need to double check the formatting/punctuation:
- Em dashes before and after “that brains can overcome brawn” in the headnote
- Em dashes in the nite on “Whence called Centaurus”
- formatting of the link to “Racoons (Emblem 21)” in the note on “Four thousand whales are forced to draw in mills”

Maybe there’s more, I didn’t check everything.

**Comment by k-poland** [comment]
The dashes are fixed by the character correction update I just pushed. Link formatting should’ve been fixed in the previous update; is it still not right?

**Comment by sergei-kalugin** [comment]
I was fixed, I had to rebuild the site to see your new changes. Thank you, @k-poland!
