### ISSUE TITLE
Publish Posterless Poems?

### ISSUE THREAD

**Issue by sergei-kalugin** [MADStudioNU/the-pulter-project#430]
@LeahKnight @wendywall:

I hate to be in the way of the completed work to go live. Should we publish the emblems that are ready sans posters?

**Comment by LeahKnight** [comment]
@sergei-kalugin No, please take your time with the posters first, Sergei: that design element is really appreciated by users, and we like to use them in our Tweets too. There's no big rush! We know everything is in a queue and will go up when time permits.

**Comment by sergei-kalugin** [comment]
Understood. Thank you, Leah.
