### ISSUE TITLE
Poem 118: critical syntax error

### ISSUE THREAD

**Issue by sergei-kalugin** [MADStudioNU/the-pulter-project#431]
There is a critical syntax error in [Poem 118 source file](https://github.com/MADStudioNU/the-pulter-project/blob/develop/pulter-poems/pulter_118.xml) that prevents us from rebuilding the site.

@katgaro: I can check it later today but if you have time, please fix sooner. Do you use a code editor with syntax checking/highlighting features enabled? If so, it should be easy to catch this.

**Comment by katgaro** [comment]
I just checked it out and I think I resolved the problem. The links to other Pulter poems needed to be fixed. 

Let me know if there are any other issues with it that I might have missed.

**Comment by sergei-kalugin** [comment]
Looks good. The formatting of the links to curations, I think, should be different, but that’s a different issue. 

Thank you for fixing this so quickly, @katgaro !
