### ISSUE TITLE
Publish A118

### ISSUE THREAD

**Issue by wendywall** [MADStudioNU/the-pulter-project#433]
Oops. I mean A118. Sorry, Sergei.

**Comment by LeahKnight** [comment]
@wendywall A018 is already published - is this a typo?

**Comment by LeahKnight** [comment]
@wendywall  ... for Whitney's A118, perhaps?

**Comment by LeahKnight** [comment]
@wendywall ... if it is indeed A118 that you mean, we should pause until the corresponding Curations are ready, as per Whitney's request. Guessing this is right, I've put the "not yet" label on here for now; feel free to amend the poem number in the header if my guess is correct.

**Comment by sergei-kalugin** [comment]
Re-naming and re-opening this. Is this still a "not yet" issue?

**Comment by wendywall** [comment]
Hi, Sergei,

Hope that you are doing well in our sauna-weather these days.

See github #411. If this is resolved, then this poem can be published.

Wendy


Wendy Wall
Co-director with Leah Knight
The Pulter Project: Poet in the Making<http://pulterproject.northwestern.edu/>
(Follow: @PulterProject)

Director, Kaplan Institute for the Humanities
Avalon Foundation Professor of the Humanities
Charles Deering McCormick Professor of Teaching Excellence

**Comment by sergei-kalugin** [comment]
@wendywall @LeahKnight 

This has been published.

https://pulterproject.northwestern.edu/poems/ae/the-snail-the-tulip-and-the-bee-emblem-53/

![Screen Shot 2020-08-12 at 4 54 30 PM](https://user-images.githubusercontent.com/2558705/90072175-8e71b380-dcbc-11ea-8d86-de88c179b0dc.png)
