### ISSUE TITLE
Alphabetize poem tags for poems 21-120

### ISSUE THREAD

**Issue by sergei-kalugin** [MADStudioNU/the-pulter-project#435]

**Comment by LeahKnight** [comment]
@sergei-kalugin Is this a task that could be assigned to Katrina or Sam perhaps, Sergei?

**Comment by sergei-kalugin** [comment]
Sure. Don't do it manually, though. I think it's worth an effort to research a text editor or plugin that can semi-automate this task.

**Comment by LeahKnight** [comment]
@sergei-kalugin Thanks for the tip. Can you clarify the assignment? Are you wanting things alphabetized in the code in GH, or in the metadata sheet?

**Comment by sergei-kalugin** [comment]
Right now, the filter tags on the index page are in random order: we should alphabetize them in the source code, yes. I'm going to look at how we can automate this task later.

Note: the keywords should stay intact since the order there is intentional.

**Comment by sergei-kalugin** [comment]
Completed for poems 1-20

**Comment by sergei-kalugin** [comment]
Completed for 21-60

**Comment by sergei-kalugin** [comment]
Completed for 61-100

**Comment by sergei-kalugin** [comment]
Completed for 101-120
