### ISSUE TITLE
Poem 117: add poster

### ISSUE THREAD

**Issue by lhn4977** [MADStudioNU/the-pulter-project#451]

**Comment by lhn4977** [comment]
@sergei-kalugin bump?

**Comment by sergei-kalugin** [comment]
@lhn4977 @wendywall @LeahKnight 

https://pulterproject-dev-4slasb7dfnyuier8z7y2.netlify.app/poems/ee/the-caucasines-emblem-52/

**Comment by sergei-kalugin** [comment]
@LeahKnight @syreeves 

https://pulterproject-dev-4slasb7dfnyuier8z7y2.netlify.app/poems/ee/the-caucasines-emblem-52/

The dark image seems to be a little bit too bright, no?

**Comment by syreeves** [comment]
The dark image does compete with the white text - I can definitely knock it down a bit.

**Comment by sergei-kalugin** [comment]
@LeahKnight: could you please give your final blessing to this one?

https://pulterproject-dev-4slasb7dfnyuier8z7y2.netlify.app/poems/ee/the-caucasines-emblem-52/

**Comment by LeahKnight** [comment]
Blessings be upon it, @sergei-kalugin @syreeves

**Comment by sergei-kalugin** [comment]
https://pulterproject.northwestern.edu/poems/ee/the-caucasines-emblem-52/
