### ISSUE TITLE
Poem 90: publish T&EE

### ISSUE THREAD

**Issue by wendywall** [MADStudioNU/the-pulter-project#453]

**Comment by sergei-kalugin** [comment]
Looks like E090 is already in preview: https://pulterproject-dev-4slasb7dfnyuier8z7y2.netlify.app/poems/ee/this-flying-fish-emblem-25/

**Comment by wendywall** [comment]
Oops. Yes, I meant publish to the world with poster. Thanks!

**Comment by sergei-kalugin** [comment]
@wendywall @LeahKnight 

Please check the poster. I'll publish the poem once you approve.

https://pulterproject-dev-4slasb7dfnyuier8z7y2.netlify.app/poems/ee/this-flying-fish-emblem-25/

**Comment by LeahKnight** [comment]
@sergei-kalugin  Looks great -- thanks!

**Comment by sergei-kalugin** [comment]
@LeahKnight @wendywall: this has been published.

https://pulterproject.northwestern.edu/poems/ee/this-flying-fish-emblem-25/

![Screen Shot 2020-08-11 at 4 13 35 PM](https://user-images.githubusercontent.com/2558705/89949528-a4fd0980-dbed-11ea-8f0b-a1ba703d5d00.png)
