### ISSUE TITLE
Poem 113: publish poster

### ISSUE THREAD

**Issue by katgaro** [MADStudioNU/the-pulter-project#454]

**Comment by syreeves** [comment]
@sergei-kalugin poster images are in the repo

**Comment by sergei-kalugin** [comment]
Uploaded to preview!

https://pulterproject-dev-4slasb7dfnyuier8z7y2-old.netlify.app/poems/ee/the-oyster-and-the-mouse-emblem-48/

**Comment by LeahKnight** [comment]
@sergei-kalugin looks good -- please publish.
