### ISSUE TITLE
Poem 120: Move T&EE to preview

### ISSUE THREAD

**Issue by LeahKnight** [MADStudioNU/the-pulter-project#461]

**Comment by sergei-kalugin** [comment]
@lhn4977: this has been added, right? Should I publish to preview?

**Comment by sergei-kalugin** [comment]
@LeahKnight, @wendywall: what is the title of this poem? Right now we have conflicting “Somnus, Why Art Thou Still to Me Unkind?” in the index and “Somnus” in the poem data.

**Comment by sergei-kalugin** [comment]
@LeahKnight @wendywall: published to preview as “Somnus”:

https://pulterproject-dev-4slasb7dfnyuier8z7y2.netlify.app/poems/ee/somnus-why-art-thou-still-to-me-unkind/

**Comment by wendywall** [comment]
Thanks for catching this discrepancy, Sergei. Leah, perhaps on the model of Poem 40,  and 49 (and maybe 50) we should standardize the title to “Somnus, Why Art Thou Still to Me Unkind.” What do you think?

Wendy


Wendy Wall
Co-director with Leah Knight
The Pulter Project: Poet in the Making<http://pulterproject.northwestern.edu/>
(Follow: @PulterProject)
Avalon Foundation Professor of the Humanities
Northwestern University

**Comment by LeahKnight** [comment]
@sergei-kalugin @wendywall The title should be “Somnus, Why Art Thou Still to Me Unkind?”

**Comment by LeahKnight** [comment]
@sergei-kalugin @k-poland @wendywall A separate issue that Sam flagged (somewhere): she needs help with linking to the MS images, b/c these lack Photo IDs, b/c the poem is recorded not in the volume but in loose sheets. (That's how she summarized it for me.) She hoped Katie might know what to do.

**Comment by sergei-kalugin** [comment]
Closing this and moving Leah's issue to #465
