### ISSUE TITLE
Poem 120: Fix overlapping marginal text in single-version view

### ISSUE THREAD

**Issue by LeahKnight** [MADStudioNU/the-pulter-project#466]
"Nereus" and "Doris", 2 words in the left margin, overlap the main text in the single-version view (they look fine in the comparison view). @sergei-kalugin or @k-poland , we'd be grateful if you could work your magic at some point (no rush).

**Comment by sergei-kalugin** [comment]
@LeahKnight, @k-poland: this is fixed.

https://pulterproject-dev-4slasb7dfnyuier8z7y2.netlify.app/poems/ee/somnus-why-art-thou-still-to-me-unkind/
