### ISSUE TITLE
Scholarship page update #2

### ISSUE THREAD

**Issue by katgaro** [MADStudioNU/the-pulter-project#468]
Correcting info in Connolly citation and moving it from 2016 to 2019

**Comment by sergei-kalugin** [comment]
@katgaro: is this something that just needs to be published or you need me to implement the updates?

**Comment by katgaro** [comment]
@sergei-kalugin this is something that needs to be published. I have already made the changes.

**Comment by sergei-kalugin** [comment]
Got you, this should be published to the preview site now.
