### ISSUE TITLE
Poem 12: T&EE Push to Preview

### ISSUE THREAD

**Issue by lhn4977** [MADStudioNU/the-pulter-project#488]

**Comment by sergei-kalugin** [comment]
Thank you, Sam! I'll get to this ASAP.

**Comment by sergei-kalugin** [comment]
@LeahKnight @wendywall: just checking, the newly added EE is by your tandem or by Fran Dolan?

**Comment by KnightLeah** [comment]
The EE is by Wendy and me.

**Comment by sergei-kalugin** [comment]
Got you! Thanks!

**Comment by sergei-kalugin** [comment]
https://pulterproject-dev-4slasb7dfnyuier8z7y2.netlify.app/poems/ee/the-garden-or-the-contention-of-flowers/
