### ISSUE TITLE
Poem 12: add poem specific styles for sub-section headers 

### ISSUE THREAD

**Issue by sergei-kalugin** [MADStudioNU/the-pulter-project#490]

**Comment by KnightLeah** [comment]
Do you mean as with "Water" etc. in Poem 41? If so, then yes please, @sergei-kalugin

**Comment by sergei-kalugin** [comment]
@lhn4977 : in [*Invocation of the Elements* (Poem 41)](https://pulterproject.northwestern.edu/poems/ee/the-invocation-of-the-elements/) we have similar section markers. Will you be able to encode ones in Poem 12 similarly?

![Screen Shot 2020-11-03 at 3 48 37 PM](https://user-images.githubusercontent.com/2558705/98044206-237fd680-1dec-11eb-81ec-5cc6ba316151.png)
![Screen Shot 2020-11-03 at 3 48 32 PM](https://user-images.githubusercontent.com/2558705/98044208-237fd680-1dec-11eb-8768-b7491b373d31.png)
 
etc.

**Comment by lhn4977** [comment]
@sergei-kalugin  Thanks for flagging this, Sergei. The codes for P12 have been updated, could you please push it to preview again? Many thanks!

**Comment by KnightLeah** [comment]
Yes, and let us know when you have done, please, @sergei-kalugin ; @katgaro is then going to do a second run of proofing on theT&EE for Poem 12. Thanks!

**Comment by sergei-kalugin** [comment]
@LeahKnight, @katgaro, @lhn4977 : the most recent update has been published to preview:

https://pulterproject-dev-4slasb7dfnyuier8z7y2.netlify.app/poems/ee/the-garden-or-the-contention-of-flowers/

**Comment by sergei-kalugin** [comment]
I will have to adjust the positioning of the words in the gutter "manually"

**Comment by sergei-kalugin** [comment]
@LeahKnight @wendywall : this is now taken care of. One of the sub-headers, though, is a bit long and looks somewhat awkward (see below), let me know if this is unacceptable.

https://pulterproject-dev-4slasb7dfnyuier8z7y2.netlify.app/poems/ee/the-garden-or-the-contention-of-flowers/

~
![Screen Shot 2020-11-09 at 4 20 18 PM](https://user-images.githubusercontent.com/2558705/98603467-b4045e00-22a7-11eb-9d56-bf387c0453b6.png)

**Comment by KnightLeah** [comment]
@sergei-kalugin Looks great to me, and ready to publish! Thanks for this fast work.

**Comment by wendywall** [comment]
Thanks, Sergei. I’m under the weather but am catching up soon. #12 looks great.
Wendy

Wendy Wall
Co-director with Leah Knight
The Pulter Project: Poet in the Making<http://pulterproject.northwestern.edu/>
(Follow: @PulterProject)
Avalon Foundation Professor of the Humanities
Northwestern University
