### ISSUE TITLE
Poem 12: publish

### ISSUE THREAD

**Issue by sergei-kalugin** [MADStudioNU/the-pulter-project#491]

**Comment by lhn4977** [comment]
@sergei-kalugin I just made two final changes to the codes. I think they're ready now (if everyone's happy with the margin!)

**Comment by sergei-kalugin** [comment]
@LeahKnight, @wendywall 

@lhn4977 : I pushed your changes to the preview, please take a last look. Will publish once your blessing is received.

**Comment by lhn4977** [comment]
@sergei-kalugin I think it's ready! Thanks so much for your work, Sergei.

**Comment by sergei-kalugin** [comment]
@wendywall @LeahKnight @lhn4977 

This has been published, congratulations on the major milestone, everyone!

https://pulterproject.northwestern.edu/poems/ee/the-garden-or-the-contention-of-flowers/

![Screen Shot 2020-11-10 at 4 12 27 PM](https://user-images.githubusercontent.com/2558705/98739757-91d61300-236f-11eb-8ed3-027af8b2ed38.png)
