### ISSUE TITLE
Poem 65: extra markup

### ISSUE THREAD

**Issue by sergei-kalugin** [MADStudioNU/the-pulter-project#494]

**Comment by sergei-kalugin** [comment]
Not sure what's going on here.

**Comment by emwitty** [comment]
yes looks like there is a whole second copy of #a2 published at the end of the TEI. It should probably just be deleted.

**Comment by sergei-kalugin** [comment]
@k-poland, I'm not sure if you're still actively involved with the project team but I'm trying to figure out what's going with this poem. It looks like there is a whole bunch of markup looking like copy-paste leftovers that don't need to be there. Can you confirm/reject?

The file right now: https://github.com/MADStudioNU/the-pulter-project/blob/develop/pulter-poems/pulter_065.xml

The commit that adds suspicious lines: https://github.com/MADStudioNU/the-pulter-project/commit/b638af8e82acd27eb249a01688247fe984346189.

**Comment by sergei-kalugin** [comment]
> yes looks like there is a whole second copy of #a2 included at the end of the parallelly-segmented TEI (which already includes a2). It should probably just be deleted.

Yes, ok, Thanks @emwitty!
