### ISSUE TITLE
Poem 68: what happened (or didn't happen) to image in the headnote?

### ISSUE THREAD

**Issue by sergei-kalugin** [MADStudioNU/the-pulter-project#496]
I and @lhn4977 realized that we have [an image](https://docs.google.com/document/d/1kR-tCsLzCl4ZUEpFIYhVisMUwRcjaoavi04f0qcFG6k/edit) that presumably belongs to the headnote of [A068 by Millie and Sarah](https://docs.google.com/document/d/1a2vEUaPFVwnZgUwlc1Ul-2PHt1gU_Dy46Wo6i8vskUE/edit) but we don't remember if we ever included it?

![Screen Shot 2020-12-01 at 9 55 40 AM](https://user-images.githubusercontent.com/2558705/100763931-6ae18e80-33bb-11eb-9fe2-abcda9e652d8.png)

**Comment by KnightLeah** [comment]
Yep, we tucked it into a Curation when it wouldn't display properly in the comparison view's headnote! All good.

**Comment by sergei-kalugin** [comment]
Got you, @KnightLeah. Thank you so much for the clarification!
