### ISSUE TITLE
“Manuscript Ambiguities”: Get a better image of the table

### ISSUE THREAD

**Issue by sergei-kalugin** [MADStudioNU/the-pulter-project#502]
Merge with #493, perhaps

**Comment by sergei-kalugin** [comment]
@LeahKnight: I know I'm blind, but can you point me to a table in a curation? I'm looking to close this ASAP.

**Comment by LeahKnight** [comment]
@sergei-kalugin I believe this was for the new Curation that Liza was working on ("Manuscript Ambiguities"), found at the top of this G Doc: https://docs.google.com/document/d/1tcxf6Ih7PlpkBqfl02t5sk5wuAMWKZTO9Po_IDpwxCM/edit

**Comment by sergei-kalugin** [comment]
OK, thank you for this link. It looks like this is going to be resolved once the encoding of “Manuscript Ambiguities” is done.

**Comment by sergei-kalugin** [comment]
Looks like an image of a table instead of an actual table works pretty well, no?


![Screen Shot 2021-02-23 at 9 18 22 AM](https://user-images.githubusercontent.com/2558705/108866028-6e02aa00-75b9-11eb-9281-cc60f5e426cb.png)

**Comment by LeahKnight** [comment]
@sergei-kalugin Yes, I think so, though the resolution seems a bit low. We'll see what Liza thinks once this item is ready for her to proofread.
