### ISSUE TITLE
Poem 65 Version B: bolded punctuations are hard to catch

### ISSUE THREAD

**Issue by sergei-kalugin** [MADStudioNU/the-pulter-project#509]
Suggest using more profound highlighting.

**Comment by LeahKnight** [comment]
Let's pause and let Liza weigh in on the issue--she's proofreading her Versions B-D now, and I've alerted her to the issue.

**Comment by LeahKnight** [comment]
@sergei-kalugin Liza likes this suggestion, and suggests using colour AND bolding as a way to make the punctuation pop.

**Comment by sergei-kalugin** [comment]
@LeahKnight: how about this?

https://pulterproject-dev-4slasb7dfnyuier8z7y2.netlify.app/poems/ae/the-hope/#a2

**Comment by LeahKnight** [comment]
@sergei-kalugin  Perfect!
