### ISSUE TITLE
Publish Updates for C006 and A104

### ISSUE THREAD

**Issue by katgaro** [MADStudioNU/the-pulter-project#513]
Updated links in Aylin Malcolm's Curation "The Unicorn" for Poem 6, and Amplified Edition for Poem 104

**Comment by sergei-kalugin** [comment]
@katgaro: do these changes need to go live, or we're just updating the preview?

**Comment by sergei-kalugin** [comment]
The preview has been updated. Let me know if this is good to push live.

**Comment by LeahKnight** [comment]
@sergei-kalugin Good to push live, thanks!
