### ISSUE TITLE
C65 Manuscript Ambiguities: Hyperlinks

### ISSUE THREAD

**Issue by lhn4977** [MADStudioNU/the-pulter-project#515]
Hyperlinks things that are highlighted in yellow here: https://docs.google.com/document/d/1tcxf6Ih7PlpkBqfl02t5sk5wuAMWKZTO9Po_IDpwxCM/edit

- Paragraph 1: Headnotes to Poem 65, Amplified Editions B, C, and D 
- Paragraph 2: Amplified Editions B, C, and D
- Last paragraph: Amplified Edition C, Amplified Edition D

**Comment by sergei-kalugin** [comment]
@lhn4977: is it ok to open those links in a new tab/window?

**Comment by lhn4977** [comment]
@sergei-kalugin I think so?

**Comment by LeahKnight** [comment]
@sergei-kalugin @lhn4977 Definitely - thanks!
