### ISSUE TITLE
C64 Pulter Reads Eikon Basilike: larger image (no whitespace around it)?

### ISSUE THREAD

**Issue by sergei-kalugin** [MADStudioNU/the-pulter-project#521]
Feels like we deserve a closer view of _Eikon_, no?

![Screen Shot 2021-02-22 at 10 05 48 AM](https://user-images.githubusercontent.com/2558705/108735074-b9538480-74f5-11eb-9867-89dcb2100d40.png)

**Comment by LeahKnight** [comment]
Definitely! The source image (massive) is here: https://luna.folger.edu/luna/servlet/detail/FOLGERCM1~6~6~62945~104804:Eikon-basilike--The-pourtraicture-o?sort=call_number%2Cmpsortorder1%2Ccd_title%2Cimprint&qvq=q:9368;sort:call_number%2Cmpsortorder1%2Ccd_title%2Cimprint;lc:FOLGERCM1~6~6&mi=0&trs=1

@sergei-kalugin @lhn4977

**Comment by sergei-kalugin** [comment]
@LeahKnight: thanks

@lhn4977: I'll update the image!

**Comment by sergei-kalugin** [comment]
https://pulterproject-dev-4slasb7dfnyuier8z7y2.netlify.app/poems/ee/and-must-the-sword-this-controverse-decide/#pulter-reads-eikon-basilike
