### ISSUE TITLE
C64s: bundle them up?

### ISSUE THREAD

**Issue by sergei-kalugin** [MADStudioNU/the-pulter-project#522]
@LeahKnight: Just making sure the four new C64s are truly meant to be individual pieces as opposed to a one “what-might-have-been-in-pulters-libratry” curation.

**Comment by sergei-kalugin** [comment]
See here: https://pulterproject-dev-4slasb7dfnyuier8z7y2.netlify.app/poems/ee/and-must-the-sword-this-controverse-decide/

**Comment by LeahKnight** [comment]
A good idea, @sergei-kalugin - thanks for it! I've asked @wendywall via email; will let you know.

**Comment by LeahKnight** [comment]
@sergei-kalugin The editor would like to keep them as is--so that's less work, at least! ;)
