### ISSUE TITLE
Elizabeth Sauer: add bio link

### ISSUE THREAD

**Issue by sergei-kalugin** [MADStudioNU/the-pulter-project#526]
@LeahKnight : perhaps Elizabeth desires to provide a link to her profile?

**Comment by LeahKnight** [comment]
Good point - thanks, Sergei! Here it is: https://brocku.ca/humanities/english-language-and-literature/faculty/elizabeth-sauer/#wip

**Comment by sergei-kalugin** [comment]
Thank you, Leah!
