### ISSUE TITLE
Poem 12: EE and T update preview and publish

### ISSUE THREAD

**Issue by katgaro** [MADStudioNU/the-pulter-project#527]

**Comment by sergei-kalugin** [comment]
https://pulterproject-dev-4slasb7dfnyuier8z7y2.netlify.app/poems/ee/the-garden-or-the-contention-of-flowers/

**Comment by sergei-kalugin** [comment]
@katgaro : this needs to be published on the "preview" site only, right?

**Comment by katgaro** [comment]
Yes! Sorry for the mix-up. Thanks
