### ISSUE TITLE
C64s: italicize title of books in Curation headers (instead of inside quotation marks)

### ISSUE THREAD

**Issue by lhn4977** [MADStudioNU/the-pulter-project#528]
If I click on the Curation, the book titles are italicized, but in preview, they're inside quotation marks. Any insights, Sergei?

<img width="1058" alt="Screen Shot 2021-02-25 at 4 54 32 PM" src="https://user-images.githubusercontent.com/60200898/109135919-28e1a200-778a-11eb-8f69-e245e6168a04.png">

**Comment by sergei-kalugin** [comment]
![Screen Shot 2021-02-25 at 11 08 24 AM](https://user-images.githubusercontent.com/2558705/109189606-d38d9c80-7759-11eb-8e80-86914f716b13.png)


https://pulterproject-dev-4slasb7dfnyuier8z7y2.netlify.app/poems/ee/and-must-the-sword-this-controverse-decide/#ctxs
