### ISSUE TITLE
Poem 65 (B, C, D): move text from poem’s headnote to editorial note

### ISSUE THREAD

**Issue by sergei-kalugin** [MADStudioNU/the-pulter-project#529]
Opinion: a lot of the headnote prose in B, C, D concerns editorial choices, etc., and should be moved to the place that was designed to harbor it — the Editorial Note. This will significantly improve the approachability of these editions.

**Comment by LeahKnight** [comment]
Thanks for the suggestion, @sergei-kalugin. In these particular editions, it's true, some headnote and editorial note matters can interweave at times -- but given the approach taken here, that's a feature, rather than a bug, in AEs B-D.
