### ISSUE TITLE
Poem 65 AE(b): add support for preserving whitespace

### ISSUE THREAD

**Issue by sergei-kalugin** [MADStudioNU/the-pulter-project#532]
Liza wants the option of whitespace not being collapsed in the poem text but collapsed in the note headers. Looks like we need to add a couple of `rend` classes for `tei:seg` to handle at least these scenarios: 

- if not collapsed in the poem, don't collapse in the note (default?)
- not collapsed in the poem, but collapsed in the note (AE65b’s case)
- other cases?

**Comment by sergei-kalugin** [comment]
@lhn4977: do you mind checking if this is the expected behavior, please?

https://pulterproject-dev-4slasb7dfnyuier8z7y2.netlify.app/poems/ae/the-hope/#a2


![Screen Shot 2021-03-01 at 12 32 07 PM](https://user-images.githubusercontent.com/2558705/109542371-96434a80-7a8a-11eb-9241-872519c1459e.png)

**Comment by LeahKnight** [comment]
@sergei-kalugin If you mean the single spacing in "of nothing recreate," in the note header, then: yes! I believe this is what is wanted.
