### ISSUE TITLE
Poem 65 (AEs B,C,D): AE mis-titled in Comparison View

### ISSUE THREAD

**Issue by lhn4977** [MADStudioNU/the-pulter-project#535]
Under the "Sources" box, under "Versions", the Amplified Editions should be lettered A-D?
![1cU4fceXWKodGJVqfWd_ln7DPJsJ3__7Y-V7R4jWi](https://user-images.githubusercontent.com/60200898/109779836-f1b33b00-7c38-11eb-9a5a-d499cf071ddb.png)

**Comment by LeahKnight** [comment]
Yes: thanks, Sam! @emwitty maybe this is one for you?

**Comment by emwitty** [comment]
@LeahKnight It looks like this reflects an earlier decision when initially using numbers to enumerate multiple amplified editions, hence our use of the 'ae' 'a2' 'a3' 'a4' labeling.   Should the use of A, B, C, D, ... be used globally, i.e. also in the navigation of Poem 10?  Probably...

**Comment by LeahKnight** [comment]
@emwitty Yes, good plan, Matt! Should I make a separate GH issue re Poem 10 on this front?

**Comment by emwitty** [comment]
@LeahKnight Makes sense. This issue is sufficient ~ thank you

**Comment by emwitty** [comment]
proposed fix deployed to preview site for testing
