### ISSUE TITLE
Poem 65 (AEs B,C,D): headnote jumplinks don't work

### ISSUE THREAD

**Issue by lhn4977** [MADStudioNU/the-pulter-project#538]
From Liza: The "bottom of this headnote" jumplink in the Headnote doesn't work in any of the three editions, in comparison mode. If you can't make jumplink work in Comparison mode, perhaps add back the phrase ", after the three asterisks (***)" after "bottom of this Headnote".

**Comment by emwitty** [comment]
I've added anchoring to VM, but clicking the anchor produces a non-ideal result that may be more difficult to solve. Clicking the anchor moves down the page scroll view to put the three *** at the top of the window, but unfortunately, then the content is hidden underneath the header graphic, title, and panel selectors, requiring scrolling back up. May not be easily fixable without changes to VM's design.

**Comment by emwitty** [comment]
>  May not be easily fixable without changes to VM's design.
Or ... maybe just add `scroll-margin-top` specification to CSS ?

**Comment by emwitty** [comment]
proposed fix deployed to preview site for testing
