### ISSUE TITLE
Publish AE and Curations for Poem 64

### ISSUE THREAD

**Issue by LeahKnight** [MADStudioNU/the-pulter-project#541]

**Comment by sergei-kalugin** [comment]
https://pulterproject.northwestern.edu/poems/ae/and-must-the-sword-this-controverse-decide/


![Screen Shot 2021-03-03 at 11 18 57 AM](https://user-images.githubusercontent.com/2558705/109844986-498a7b80-7c12-11eb-90ae-7520cb28f2a5.png)
