### ISSUE TITLE
Poem 64 (AE): Hyperlinks to Curations in notes blocks italicization

### ISSUE THREAD

**Issue by lhn4977** [MADStudioNU/the-pulter-project#543]
In notes on "widows' and poor orphans'", "chosen ones", "Orb of love", "Time's fair Virgin Daughter", there are hyperlinks to Curations. "Tenth Muse," "Emblemes" should be italicized (and they are in the codes) but not italicized in view. 

Any ideas?

**Comment by sergei-kalugin** [comment]
@lhn4977 got you, will look into it

**Comment by lhn4977** [comment]
@sergei-kalugin thank you! you're a hero.

**Comment by sergei-kalugin** [comment]
https://pulterproject.northwestern.edu/poems/ae/and-must-the-sword-this-controverse-decide/#0
