### ISSUE TITLE
Update Scholarship page

### ISSUE THREAD

**Issue by lhn4977** [MADStudioNU/the-pulter-project#544]

**Comment by sergei-kalugin** [comment]
@lhn4977: this is a "hotfix" (it needs to be applied to both preview and the production site), right?

**Comment by lhn4977** [comment]
@sergei-kalugin yes please! thank you!

**Comment by LeahKnight** [comment]
@sergei-kalugin Thank you for doing this! 

I made just a few tiny fixes to the code just now, which I guess will need a shove into the light of day!
