### ISSUE TITLE
C12 Flower People: Poem Stanza Breaks not shown

### ISSUE THREAD

**Issue by lhn4977** [MADStudioNU/the-pulter-project#554]
I believe the stanza breaks are encoded, but not reflected in the preview. Any idea why this might be the case, @emwitty??

**Comment by emwitty** [comment]
@lhn4977 I'm sorry - can you be more specific as to which poem(s) you mean?  I'd also like to compare them to the GoogleDocs version, but I'm not sure (a) that I have the link to it, and that (b) I have permission to see it with my mtaylor@northwestern.edu Google account.

**Comment by LeahKnight** [comment]
@emwitty She's referring to Poem 12, a Curation called "Flower People," by Fran Dolan: https://docs.google.com/document/d/1DBQDmfL-46ofUIcu1gH0Zz8DwIyMrA4NBzHjmtn0398/edit

**Comment by emwitty** [comment]
A quick glance, I think the stanza breaks are there, but, as always subtle and possibly not readily discernible due to the line spacing.  By comparison, the stanza breaks in Phillips's "On the Death of My First and Dearest Child" https://pulterproject.northwestern.edu/poems/ee/upon-the-death-of-my-dear-and-lovely-daughter/#child-loss-elegies  are similarly subtle.

**Comment by emwitty** [comment]
In other words, this may be something of a consideration for styling of the poems (line spacing, stanza spacing) throughout the site. I don't know how much debate already went into the current metrics ... but usually there's a conversation — a group one or, at least an internal one on Sergei's part — concerning the "vertical rhythm" that has led to most of the choices we have now.

**Comment by lhn4977** [comment]
Hmm you're right. The spacing does seem very subtle in every poem. I don't know if anyone has raised this concern to Sergei but shall we do something to address the issue?

**Comment by emwitty** [comment]
We could try a few variations to the CSS on an experimental basis, but we should probably recollect Sergei in the conversation sometime after he becomes available again (after April 13).

**Comment by lhn4977** [comment]
I'd be happy to wait until Sergei is back!

**Comment by sergei-kalugin** [comment]
Hi everyone (@emwitty, @LeahKnight, @lhn4977)!

This is an overlooked side-effect of an earlier list-related style tweak. Sorry about that! Should be fixed now and I'm pushing this to prod shortly.

![Screen Shot 2021-04-15 at 5 20 20 PM](https://user-images.githubusercontent.com/2558705/114945427-eb56d800-9e0e-11eb-9177-e20e4645af2b.png)

**Comment by lhn4977** [comment]
@sergei-kalugin ohh thank you but please don't push it to prod just yet. we still need to do another round of proofreading
