### ISSUE TITLE
Update "The Project" Page

### ISSUE THREAD

**Issue by lhn4977** [MADStudioNU/the-pulter-project#560]

**Comment by sergei-kalugin** [comment]
@lhn4977 : should this update go to just the review or both preview and production?

**Comment by lhn4977** [comment]
I'd say both. Thank you Sergei!

**Comment by sergei-kalugin** [comment]
https://pulterproject.northwestern.edu/about-the-project.html

**Comment by LeahKnight** [comment]
Odd! I see it in Chrome, but not Safari -- good enough, though! :)
