### ISSUE TITLE
Anna Rebecca Lewis: add bio link once her PhD begins

### ISSUE THREAD

**Issue by sergei-kalugin** [MADStudioNU/the-pulter-project#568]
Looks like we have a new contributor (Poem 107), Anna Rebecca Lewis.

**Comment by LeahKnight** [comment]
We do! She'll start her PhD at U of T in Fall, and will update us re a bio link then.

**Comment by lhn4977** [comment]
Yep! I've already added her as a contributor on the Project page.

**Comment by LeahKnight** [comment]
Yes, understood, @sergei-kalugin ; Anna has confirmed that she does not have a personal/institutional profile link at the moment, or in the offing, so the issue seemed close-able.

**Comment by sergei-kalugin** [comment]
Got you! Thank you for the clarification!
