### ISSUE TITLE
A107: Push to preview

### ISSUE THREAD

**Issue by syreeves** [MADStudioNU/the-pulter-project#573]
@sergei-kalugin @LeahKnight

**Comment by sergei-kalugin** [comment]
The poem is already in preview. Dis you mean the updates, @syreeves?

**Comment by sergei-kalugin** [comment]
https://pulterproject-dev-4slasb7dfnyuier8z7y2.netlify.app/poems/ae/this-huge-leviathan-emblem-42/

**Comment by syreeves** [comment]
I realized I just misread Leah's email. I will create a new issue.
