### ISSUE TITLE
A055: Publish

### ISSUE THREAD

**Issue by LeahKnight** [MADStudioNU/the-pulter-project#575]
@sergei-kalugin

**Comment by sergei-kalugin** [comment]
<img width="252" alt="Screen Shot 2021-05-03 at 11 56 12 AM" src="https://user-images.githubusercontent.com/2558705/116907050-abf9fb00-ac06-11eb-9439-93f6107e9108.png">
<img width="379" alt="Screen Shot 2021-05-03 at 11 55 59 AM" src="https://user-images.githubusercontent.com/2558705/116907053-ac929180-ac06-11eb-83ec-b95047a2c22e.png">
<img width="351" alt="Screen Shot 2021-05-03 at 11 55 45 AM" src="https://user-images.githubusercontent.com/2558705/116907055-ad2b2800-ac06-11eb-9b1e-19a104e8838e.png">

**Comment by LeahKnight** [comment]
The first thing (the dashes) we can leave as is, Sergei -- but thanks for reminding me about the need to fix the numbering in the title!

**Comment by sergei-kalugin** [comment]
@LeahKnight : yes, I wasn't sure about the dashes. Is it part of the "Canadian spelling" that Kenneth mentions in his Editorial Note?

**Comment by LeahKnight** [comment]
Not specifically Canadian, nope: it's just an available style (apparently recommended by the Associated Press: https://prowritingaid.com/grammar/1000066/Should-I-use-spaces-around-an-em-dash). I figure he can use that kind of dash if he wants, as part of the idea that AE editors get to pick their style (unlike in Curations, say).

**Comment by sergei-kalugin** [comment]
@LeahKnight : Oh, I wasn't actually referring to space before and after the dashes but rather to the use of an **en** dash instead of an **em** dash. Do we also allow that?

**Comment by LeahKnight** [comment]
Oh: sorry, Sergei! I don't suppose we do, no. @katgaro : would you mind, after all, amending Ken's A055 G Doc to feature em-dashes instead of en-dashes as needed, and amending the code to match? Thanks!

**Comment by katgaro** [comment]
@LeahKnight @sergei-kalugin Not a problem. Should I change the dashes in the poem as well?

**Comment by sergei-kalugin** [comment]
I think so, but I'll let one Canadian (@LeahKnight) speak for another.

**Comment by LeahKnight** [comment]
I've checked with Ken, and he's good with en-dashes becoming em-dashes, with no space on either side. @katgaro , would you mind handling this? And/or the numbering in the x-references (flagged above)?

**Comment by katgaro** [comment]
I can handle it, yep. Should be pretty quick fixes so I'll do them asap

**Comment by katgaro** [comment]
Changes are made! All dashes should now be em-dashes, and the poem refs should no longer contain extra numbers

**Comment by LeahKnight** [comment]
Thanks, Katrina! @sergei-kalugin push Katrina's fixes to preview for last pre-publication check, please.

**Comment by sergei-kalugin** [comment]
@LeahKnight, @katgaro:

https://pulterproject-dev-4slasb7dfnyuier8z7y2.netlify.app/poems/ae/must-i-thus-ever-interdicted-be/

**Comment by KnightLeah** [comment]
Looks great - please publish! @sergei-kalugin

**Comment by sergei-kalugin** [comment]
https://pulterproject.northwestern.edu/poems/ae/must-i-thus-ever-interdicted-be/
