### ISSUE TITLE
Poem 113: Publish updates

### ISSUE THREAD

**Issue by LeahKnight** [MADStudioNU/the-pulter-project#585]
@sergei-kalugin

**Comment by sergei-kalugin** [comment]
https://pulterproject-dev-4slasb7dfnyuier8z7y2.netlify.app/poems/ee/the-oyster-and-the-mouse-emblem-48/

**Comment by KnightLeah** [comment]
Looks good! Please publish update, @sergei-kalugin

**Comment by sergei-kalugin** [comment]
https://pulterproject.northwestern.edu/poems/ee/the-oyster-and-the-mouse-emblem-48/
