### ISSUE TITLE
C12 Other Garden Poems: push to preview

### ISSUE THREAD

**Issue by lhn4977** [MADStudioNU/the-pulter-project#593]

**Comment by sergei-kalugin** [comment]
http://localhost:3000/poems/ee/the-garden-or-the-contention-of-flowers/#other-garden-poems

**Comment by sergei-kalugin** [comment]
https://pulterproject-dev-4slasb7dfnyuier8z7y2.netlify.app/poems/ee/the-garden-or-the-contention-of-flowers/#other-garden-poems
