### ISSUE TITLE
A055: last quick fix please! 

### ISSUE THREAD

**Issue by LeahKnight** [MADStudioNU/the-pulter-project#595]
@sergei-kalugin Ken noticed a few small citation format errors; I've corrected the code, and we'd be glad if you'd please update the published version.

**Comment by sergei-kalugin** [comment]
Coming up soon.

**Comment by sergei-kalugin** [comment]
https://pulterproject.northwestern.edu/poems/ae/must-i-thus-ever-interdicted-be/
