### ISSUE TITLE
C12 Flower People & Botanical Blazon: improve formatting

### ISSUE THREAD

**Issue by lhn4977** [MADStudioNU/the-pulter-project#597]
@sergei-kalugin for Curation "Flower People," do you have a suggestion as to what to do with the one "endnote" (to "egrets" on line 47)? Right now it's sorta just inserted in between the paragraphs.
@LeahKnight these two are ready apart from the one query I have for Sergei above!

**Comment by LeahKnight** [comment]
@lhn4977 For the note on "egrets" in "Flower People": I've put the word "feathers" in square brackets immediately after "egrets" (as Fran did in the G Doc).
