### ISSUE TITLE
Curation/Exploration footnotes: add styles if not already implemented

### ISSUE THREAD

**Issue by sergei-kalugin** [MADStudioNU/the-pulter-project#602]

**Comment by lhn4977** [comment]
@lhn4977 tagging myself to keep myself updated

**Comment by sergei-kalugin** [comment]
Ok, I need to take care of this ASAP.

**Comment by sergei-kalugin** [comment]
Just a note for myself: Poem 53 Curations is where this is needed as well

**Comment by sergei-kalugin** [comment]
C107, C87, C053 are affected
