### ISSUE TITLE
C12: Rename "Images of Flowers"

### ISSUE THREAD

**Issue by sergei-kalugin** [MADStudioNU/the-pulter-project#607]
@lhn4977: did the title (and the filename) of this curation change? It used to be "Images of Flowers" and now it's "Picturing Pulter's Flowers," right? I need to update the manifest when the names change, otherwise, it won't show up on the resulting poem page. Let me know!

**Comment by lhn4977** [comment]
@sergei-kalugin that's right! Fran requested a name change.

**Comment by sergei-kalugin** [comment]
Got you. I'm gonna change it everywhere then. Thanks, @lhn4977!
