### ISSUE TITLE
Footnotes/ endnotes not numbered in Editorial Notes?

### ISSUE THREAD

**Issue by lhn4977** [MADStudioNU/the-pulter-project#610]
@sergei-kalugin I was correcting Poem 64 when I realized that footnotes/ endnotes are not numbered in Elizabeth Sauer's editorial note: http://pulterproject.northwestern.edu/poems/ae/and-must-the-sword-this-controverse-decide/

Is this the standard of the site or a formatting issue?

**Comment by LeahKnight** [comment]
That's an error; see the Ed. Note in the AE for Poem 6 for an example of note numbering.  @lhn4977

**Comment by lhn4977** [comment]
@LeahKnight thank you, it's fixed now!
