### ISSUE TITLE
A064: Publish Updates

### ISSUE THREAD

**Issue by lhn4977** [MADStudioNU/the-pulter-project#611]

**Comment by lhn4977** [comment]
@sergei-kalugin this can also be moved to production site, thanks Sergei!

**Comment by lhn4977** [comment]
@sergei-kalugin I updated the codes just now to fix the editorial notes issue. ready to be updated/ published!

**Comment by sergei-kalugin** [comment]
https://pulterproject.northwestern.edu/poems/ae/and-must-the-sword-this-controverse-decide/
