### ISSUE TITLE
"Picturing Pulter" image outline

### ISSUE THREAD

**Issue by katgaro** [MADStudioNU/the-pulter-project#619]
There is an outline around the second image in this Exploration. I'm not sure how it got there or how to remove it. @lhn4977 @sergei-kalugin any clues?

**Comment by lhn4977** [comment]
@katgaro Likely because 1) the original has an outline or 2) the width is not 800px. I'd recommend resizing the image if you haven't already (to 800px) or redownloading the source image to make sure it has no outline.

**Comment by katgaro** [comment]
Thank you! I re-uploaded the adjusted file.
