### ISSUE TITLE
C107s: move to preview

### ISSUE THREAD

**Issue by sergei-kalugin** [MADStudioNU/the-pulter-project#623]

**Comment by syreeves** [comment]
@sergei-kalugin I just uploaded the last of the C107s - they are now good to go to preview!

**Comment by sergei-kalugin** [comment]
@syreeves : could you please list the new curations here in the comments?

**Comment by syreeves** [comment]
"Whaling Legends", "Did hunters really ride whales like horses?", "Whales Working in Mills", "The Leviathan and the Bible", "Taming the North American Indian", and "The Miracle of the Swine"

**Comment by sergei-kalugin** [comment]
https://pulterproject-dev-4slasb7dfnyuier8z7y2-old.netlify.app/poems/ee/this-huge-leviathan-emblem-42/#ctxs
