### ISSUE TITLE
References to Curation & Explorations

### ISSUE THREAD

**Issue by sergei-kalugin** [MADStudioNU/the-pulter-project#627]

**Comment by sergei-kalugin** [comment]
To reference a curation that is located on the same page as the poem we are referencing from we have the following TEI syntax:
`<ref type="pp-curations-ref" target="#ctxs">The Poetry of Night and Day</ref>`

To reference an external curation/exploration we have the following for TEI (poems):
`<ref type="pp-curation-ref" target="/poems/ae/aurora-2/#the-poetry-of-night-and-day">The Poetry of Night and Day</ref>`

and this for HTML (curations, explorations, pages etc.):
`<a class="pp-curation-ref" href="/poems/ae/aurora-2/#the-poetry-of-night-and-day" target="_blank">The Poetry of Night and Day</a>`

**Comment by syreeves** [comment]
I will update our encoding guides to reflect this!
