### ISSUE TITLE
Poem 118: reference to a non-existing Curation

### ISSUE THREAD

**Issue by sergei-kalugin** [MADStudioNU/the-pulter-project#628]
@LeahKnight: In the note on "active Amazonian maid" ([line 7](https://pulterproject.northwestern.edu/poems/ae/the-snail-the-tulip-and-the-bee-emblem-53/#tppl-ae-7)) we have a reference to a curation titled *The Political Bee*. Is it something we expect to receive in the future?

<img width="433" alt="Screen Shot 2021-05-20 at 6 07 30 PM" src="https://user-images.githubusercontent.com/2558705/119061942-295d9380-b99b-11eb-9a6d-409f0bfe6a64.png">

**Comment by LeahKnight** [comment]
Great question, @sergei-kalugin: thanks! I'm conferring with the editor on a solution.

**Comment by LeahKnight** [comment]
@katgaro will take care of this.

**Comment by LeahKnight** [comment]
Should be addressed in updated A118
