### ISSUE TITLE
A012: Update Preview

### ISSUE THREAD

**Issue by lhn4977** [MADStudioNU/the-pulter-project#629]
@LeahKnight then would you mind taking one last look before we publish the AE to the production site?

**Comment by LeahKnight** [comment]
@lhn4977 Would you please confirm: are the C012s all proofed by Fran and corrected? I ask b/c we want to publish both A012 and the C012s to production at once.

**Comment by lhn4977** [comment]
@LeahKnight not yet. I sent them to Fran so currently waiting for her to proof!

**Comment by LeahKnight** [comment]
@lhn4977 OK, great: let's hold off on reviewing A012 and pushing to production until the C012s are proofed and fixed -- thanks!
