### ISSUE TITLE
“A” Drop Cap (8 poems)

### ISSUE THREAD

**Issue by sergei-kalugin** [MADStudioNU/the-pulter-project#637]

**Comment by sergei-kalugin** [comment]
![Screen Shot 2021-05-25 at 5 08 48 PM](https://user-images.githubusercontent.com/2558705/119574977-eecd6f80-bd7b-11eb-8561-5695d156e8f7.png)

![Screen Shot 2021-05-25 at 5 08 54 PM](https://user-images.githubusercontent.com/2558705/119574986-f1c86000-bd7b-11eb-984b-6afaf9731926.png)

**Comment by sergei-kalugin** [comment]
Do we like this "A" or we want to try something else?

**Comment by LeahKnight** [comment]
@sergei-kalugin If you want to play around, feel free! I sense you'd like @syreeves to try out another option?

**Comment by syreeves** [comment]
<img width="761" alt="Screen Shot 2022-06-23 at 1 10 04 PM" src="https://user-images.githubusercontent.com/80483087/175355975-ee5e9416-dee0-4f88-a6a7-0d92dddd329c.png">

Updated "A" drop cap
