### ISSUE TITLE
“V” Drop Cap (4 poems)

### ISSUE THREAD

**Issue by sergei-kalugin** [MADStudioNU/the-pulter-project#639]

**Comment by sergei-kalugin** [comment]
I think Poem 93 has the one we liked.

![Screen Shot 2021-05-25 at 4 52 44 PM](https://user-images.githubusercontent.com/2558705/119573298-a9a83e00-bd79-11eb-8bff-3fdeb5452dc1.png)

**Comment by sergei-kalugin** [comment]
https://pulterproject-preview-c7ga82m1pzxmbn.netlify.app/poems/ee/on-the-king-s-most-excellent-majesty

---

![Screen Shot 2022-07-12 at 16 34 19](https://user-images.githubusercontent.com/2558705/178599417-ac715acb-f7ce-496a-9455-1f0c911ef0aa.png)

**Comment by syreeves** [comment]
Looks great to me! @sergei-kalugin
