### ISSUE TITLE
“E” Drop Cap (1 poem)

### ISSUE THREAD

**Issue by sergei-kalugin** [MADStudioNU/the-pulter-project#642]

**Comment by syreeves** [comment]
![Screen Shot 2021-06-10 at 1 37 35 PM](https://user-images.githubusercontent.com/80483087/121571431-01d57600-c9f1-11eb-92ee-23be39cb82f4.png)

Poem 60

**Comment by sergei-kalugin** [comment]
@LeahKnight, poem 60 technically starts with "Sir," so the "S" drop cap is used. We could overwrite that if we want. Otherwise "E" is not going to be in use (P60 is the only poem we though we'd need it).

**Comment by LeahKnight** [comment]
Good point! Looks like an easy solve--I'll close this one. Thanks, @sergei-kalugin

**Comment by sergei-kalugin** [comment]
@LeahKnight, wait, so what's the decision? Which drop cap should go with poem 60? "E" or "S"?

**Comment by LeahKnight** [comment]
What I see on the site is "S"; that seems to be the first letter of the poem (from "Sir"), so that seems right to me. Meaning no action required: right? I might be misunderstanding, though--sorry if so! @sergei-kalugin

**Comment by sergei-kalugin** [comment]
No, no, you understood everything correctly. My suspicion was that you'd feel bad for "E" since it would not see the world like others.
