### ISSUE TITLE
“S” Drop Cap (5 poems)

### ISSUE THREAD

**Issue by sergei-kalugin** [MADStudioNU/the-pulter-project#643]

**Comment by syreeves** [comment]
![Screen Shot 2021-05-26 at 2 45 17 PM](https://user-images.githubusercontent.com/80483087/119714594-0e729f80-be31-11eb-8d5a-cbc723ab5579.png)

Poem 45. Will need to cut off the second stroke in the upper right

**Comment by syreeves** [comment]
![Screen Shot 2021-06-10 at 1 40 06 PM](https://user-images.githubusercontent.com/80483087/121571705-58db4b00-c9f1-11eb-9766-b49f783ce0c1.png)

Poem 45 (will need to remove the small extra flourish at the top)

**Comment by sergei-kalugin** [comment]
We have this as an option too.

![Screen Shot 2021-06-14 at 9 55 16 AM](https://user-images.githubusercontent.com/2558705/121913041-acea7600-ccf6-11eb-992a-6b9d90c2e765.png)
