### ISSUE TITLE
“C” Drop Cap (5 poems)

### ISSUE THREAD

**Issue by sergei-kalugin** [MADStudioNU/the-pulter-project#645]

**Comment by syreeves** [comment]
![Screen Shot 2021-05-26 at 2 49 29 PM](https://user-images.githubusercontent.com/80483087/119718028-146a7f80-be35-11eb-9edc-3d62ad1a1270.png)

Poem 56

**Comment by sergei-kalugin** [comment]
<img width="599" alt="Screenshot 2023-02-23 at 2 36 17 PM" src="https://user-images.githubusercontent.com/2558705/221024285-36e93038-d30f-46ee-b0c6-a985db8c3c8a.png">
