### ISSUE TITLE
“O” Drop Cap (8 poems)

### ISSUE THREAD

**Issue by sergei-kalugin** [MADStudioNU/the-pulter-project#648]

**Comment by syreeves** [comment]
![Screen Shot 2021-06-10 at 2 15 01 PM](https://user-images.githubusercontent.com/80483087/121576288-3992ec80-c9f6-11eb-81d6-c6d17131a50e.png)

Poem 52 7610_151

**Comment by sergei-kalugin** [comment]
![Screen Shot 2021-06-14 at 9 54 33 AM](https://user-images.githubusercontent.com/2558705/121912897-904e3e00-ccf6-11eb-93cf-3ff90306669f.png)
