### ISSUE TITLE
“M” Drop Cap (9 poems)

### ISSUE THREAD

**Issue by sergei-kalugin** [MADStudioNU/the-pulter-project#650]

**Comment by sergei-kalugin** [comment]
![Screen Shot 2021-05-25 at 5 10 36 PM](https://user-images.githubusercontent.com/2558705/119575133-2dfbc080-bd7c-11eb-9d9f-966adf009580.png)

![Screen Shot 2021-05-25 at 5 10 41 PM](https://user-images.githubusercontent.com/2558705/119575142-318f4780-bd7c-11eb-80f7-b6868cea7a4b.png)

**Comment by sergei-kalugin** [comment]
Looks cute, no?

**Comment by LeahKnight** [comment]
@sergei-kalugin very!
