### ISSUE TITLE
“N” Drop Cap (1 poem)

### ISSUE THREAD

**Issue by sergei-kalugin** [MADStudioNU/the-pulter-project#651]

**Comment by syreeves** [comment]
![Screen Shot 2021-06-10 at 2 17 35 PM](https://user-images.githubusercontent.com/80483087/121576667-97bfcf80-c9f6-11eb-8bbd-5c2ee6943c3c.png)

Poem 4 7610_023

**Comment by sergei-kalugin** [comment]
The right curl appears to be cropped.

---

![Screen Shot 2022-11-11 at 4 40 22 PM](https://user-images.githubusercontent.com/2558705/201440426-f6821bb0-17a7-404a-9d89-2e99ff2c0c50.png)

**Comment by sergei-kalugin** [comment]
Sorry, my bad, it is only cropped at a very specific screen width. Otherwise OK!
