### ISSUE TITLE
“ﬀ” Drop Cap (1 poem)

### ISSUE THREAD

**Issue by sergei-kalugin** [MADStudioNU/the-pulter-project#654]

**Comment by syreeves** [comment]
![Screen Shot 2021-06-10 at 1 27 01 PM](https://user-images.githubusercontent.com/80483087/121570137-94751580-c9ef-11eb-80f9-0b7f5ae08d6f.png)

Poem 32. We will likely have to drop the small flourish at the top

**Comment by sergei-kalugin** [comment]
<img width="656" alt="Screenshot 2023-02-23 at 1 31 16 PM" src="https://user-images.githubusercontent.com/2558705/221011077-47085596-e495-4124-8ed2-29289b20eddb.png">
