### ISSUE TITLE
A041: Move to Preview

### ISSUE THREAD

**Issue by katgaro** [MADStudioNU/the-pulter-project#659]

**Comment by sergei-kalugin** [comment]
https://pulterproject-preview-c7ga82m1pzxmbn.netlify.app/poems/ae/the-invocation-of-the-elements-the-longest-night-in-the-year-1655/#0

**Comment by LeahKnight** [comment]
@sergei-kalugin can you re-shove this to preview, please? @katgaro and I both noticed it somehow disappear from there just now! Very odd ...

**Comment by sergei-kalugin** [comment]
@LeahKnight : the link above is not working for you?

**Comment by LeahKnight** [comment]
Actually, that one does: it's my usual "TPP Preview" shortcut that doesn't have it! This one: https://pulterproject-dev-4slasb7dfnyuier8z7y2.netlify.app/poems/ae/the-invocation-of-the-elements-the-longest-night-in-the-year-1655/

If there's a new formula for the preview site/links, we can rely on that instead! Thanks, @sergei-kalugin

**Comment by sergei-kalugin** [comment]
@LeahKnight: yes, we had to create a new preview instance of the site. The one you have bookmarked is not being updated anymore due to a bug on Netlify (the hosting company).

**Comment by LeahKnight** [comment]
@sergei-kalugin  ohhhh! Makes sense: thanks again! :)
