### ISSUE TITLE
Video poster is hidden in desktop Safari (“About Project” page)

### ISSUE THREAD

**Issue by LeahKnight** [MADStudioNU/the-pulter-project#665]
@sergei-kalugin not sure where it went!

**Comment by sergei-kalugin** [comment]
What is the page in question, @LeahKnight ? This one? 

https://pulterproject.northwestern.edu/about-the-project.html

The video loads just fine on my end.

**Comment by KnightLeah** [comment]
That's the page, @sergei-kalugin ; I'll email you what I see (since I don't know how to paste images into GH)
