### ISSUE TITLE
"About the Project" Page: Publish Updates

### ISSUE THREAD

**Issue by katgaro** [MADStudioNU/the-pulter-project#666]

**Comment by LeahKnight** [comment]
@katgaro Am I correct that this issue is complete, and this issue can be closed? If so, please feel free to close it when you reply.

**Comment by sergei-kalugin** [comment]
I think this has been published, @LeahKnight. All the changes are currently reflected on both preview and prod sites.

**Comment by LeahKnight** [comment]
Sounds right: thanks, @sergei-kalugin !
