### ISSUE TITLE
Publish C94 “Emblem Books as Parenting Guides”

### ISSUE THREAD

**Issue by katgaro** [MADStudioNU/the-pulter-project#670]

**Comment by sergei-kalugin** [comment]
https://pulterproject-preview-c7ga82m1pzxmbn.netlify.app/poems/ee/the-cuckoo-emblem-29/#ctxs

**Comment by katgaro** [comment]
Fixed images

**Comment by katgaro** [comment]
Correcting headings

**Comment by sergei-kalugin** [comment]
Looks good to publish guys?

**Comment by katgaro** [comment]
I think so. I don't see any other corrections to be made.

**Comment by LeahKnight** [comment]
Before we publish, @sergei-kalugin , I believe Rachel first needs a chance to proof and approve what is no doubt good to go; @katgaro : would you please fire her the usual request? And/or correct me if I'm wrong?

**Comment by katgaro** [comment]
@sergei-kalugin @LeahKnight Correct!! My mistake. Will send Rachel an email to proof the page and update here when it's ready.
