### ISSUE TITLE
C94: add headings

### ISSUE THREAD

**Issue by sergei-kalugin** [MADStudioNU/the-pulter-project#672]
@katgaro: these guys should become either `<h3>` or `<h4>` (`<h4>` makes more sense IMHO):

https://github.com/MADStudioNU/the-pulter-project/blob/7983a051db75748efd1cc3f795917305c2fd88f5/pulter-site/curations/c94-emblem-books-as-parenting-guides.html#L32

https://github.com/MADStudioNU/the-pulter-project/blob/7983a051db75748efd1cc3f795917305c2fd88f5/pulter-site/curations/c94-emblem-books-as-parenting-guides.html#L71

**Comment by katgaro** [comment]
Thanks, @sergei-kalugin. I'm not sure what the difference is between the headings tags, so I went with your suggestion and will see what they look like.

**Comment by sergei-kalugin** [comment]
Does this look ok to you, @katgaro?

https://pulterproject-preview-c7ga82m1pzxmbn.netlify.app/poems/ee/the-cuckoo-emblem-29/#emblem-books-as-parenting-guides

**Comment by katgaro** [comment]
Looks good @sergei-kalugin!
