### ISSUE TITLE
A053 and C053s: Update Preview

### ISSUE THREAD

**Issue by katgaro** [MADStudioNU/the-pulter-project#675]

**Comment by sergei-kalugin** [comment]
https://pulterproject-preview-c7ga82m1pzxmbn.netlify.app/poems/ae/upon-the-crown-imperial/

**Comment by katgaro** [comment]
Should be the last update

**Comment by sergei-kalugin** [comment]
Preview has been updated!

**Comment by katgaro** [comment]
Thanks @sergei-kalugin. I have a question about a link in the AE. Line 4, note on "distill" -- the link to a Poem 21 Curation titled "Alchemy and Devotion" does not work. I've tried formatting it as the encoding guide states and as an external link, but neither way has worked. Am I doing something wrong?

**Comment by sergei-kalugin** [comment]
@katgaro: yeah, a few issues, it should be 
`<ref type="pp-curation-ref" target="//pulterproject.northwestern.edu/poems/ae/the-circle-2/#alchemy-and-devotion">Alchemy and Devotion</ref>`. 

I'll update the code!
