### ISSUE TITLE
Push corrections to preview: C107s

### ISSUE THREAD

**Issue by syreeves** [MADStudioNU/the-pulter-project#683]
C107s: 
- Did hunters really ride whales like horses?
- The Leviathan and the Bible
- The Miracle of the Swine
- Taming the North American “Indian”
- Whales Working in Mills
- Whaling Legends

Thank you! @sergei-kalugin

**Comment by sergei-kalugin** [comment]
https://pulterproject-preview-c7ga82m1pzxmbn.netlify.app/poems/ee/this-huge-leviathan-emblem-42/#ctxs
