### ISSUE TITLE
A107 and C107s: Publish 

### ISSUE THREAD

**Issue by syreeves** [MADStudioNU/the-pulter-project#690]
C107s: 
- Did hunters really ride whales like horses?
- The Leviathan and the Bible
- The Miracle of the Swine
- Taming the North American "Indian"
- Whales Working in Mills
- Whaling Legends

Everything looks good to go! @sergei-kalugin

**Comment by sergei-kalugin** [comment]
https://pulterproject.northwestern.edu/poems/ae/this-huge-leviathan-emblem-42/
