### ISSUE TITLE
"DOI" links

### ISSUE THREAD

**Issue by sergei-kalugin** [MADStudioNU/the-pulter-project#693]
There's a number of links that begin with "doi:" used with HTML's `a` tag. I'm not sure what these links are and what are they referring to, but I know for sure they don't work as intended. 

@LeahKnight, can you clarify, please?

**Comment by sergei-kalugin** [comment]
A curation where I stumbled upon these is [**Did hunters really ride whales like horses?**](https://github.com/MADStudioNU/the-pulter-project/blob/develop/pulter-site/curations/c107-did-hunters-really-ride-whales-like-horses.html)

**Comment by emwitty** [comment]
These are digital object identifiers. Persistent IDs for digital works. They are like handles (hdl) and ORCIIDs. See also: https://www.doi.org/. It should be possible to postpend there IDs to the URL doi.org/ and it might work.

**Comment by emwitty** [comment]
> These are digital object identifiers. Persistent IDs for digital works. They are like handles (hdl) and ORCIIDs. See also: https://www.doi.org/. It should be possible to postpend these IDs to the URL doi.org/ and it might work.

E.g.  https://doi.org/10.1353/book.51236

**Comment by sergei-kalugin** [comment]
Thank you, @emwitty!

How would you go about converting this into a working hyperlink?

![Screen Shot 2021-07-16 at 3 49 44 PM](https://user-images.githubusercontent.com/2558705/126007142-1a3e9d20-4870-4dc1-85fe-12836c7cfb8d.png)

**Comment by emwitty** [comment]
Ha! Leave it to Oxford publishing to list a DOI for their reference works but not actually register them. I think I would leave it alone. It’s not our fault it’s broken. Other systems using DOI to link to referenced works just leave it linked to the regular DOI exception page so maybe we should too.  See below for what researchgate seems ok with:

Eg. https://www.researchgate.net/publication/315611330_The_Grove_Encyclopedia_of_American_Art

**Comment by KnightLeah** [comment]
@katgaro would you please work with Sergei on this one? He's noticed a number of broken links; see above for one location.  @sergei-kalugin , if you ID the others, Katrina can aim to replace the broken stuff with functioning links. Thanks, all!

**Comment by katgaro** [comment]
@KnightLeah Yep! I can help fix these links.

@sergei-kalugin I can check all of the DOIs we have listed and replace the ones that do not work with either the correct DOI or a link to the source. Would that help?

**Comment by sergei-kalugin** [comment]
@katgaro A working link to the source should be enough, yes!

**Comment by katgaro** [comment]
@sergei-kalugin I've corrected the DOI links in the Curation you flagged above, and requested a Preview update to make sure everything is in working order. The other links in this Curation were not working either, so I replaced those as well.

**Comment by katgaro** [comment]
@sergei-kalugin Other Curations that need updating: C46 and C81 "Lark Mirrors" (same title). 

Those are all the DOIs I found. I believe there is a link checking project in process, which I'm sure will catch any remaining links that may be broken.

**Comment by sergei-kalugin** [comment]
@katgaro, thank you!
