### ISSUE TITLE
"Hester Pulter's DOB" Exploration: Move to Preview

### ISSUE THREAD

**Issue by katgaro** [MADStudioNU/the-pulter-project#697]
Some of the images will most likely need to do be redone because they are very pixelated after resizing. @LeahKnight is already aware of this. We agreed that we should see what everything looks like and address any necessary changes from there.

**Comment by sergei-kalugin** [comment]
https://pulterproject-preview-c7ga82m1pzxmbn.netlify.app/#hester-pulters-date-of-birth
