### ISSUE TITLE
DOI corrections: Update Preview

### ISSUE THREAD

**Issue by katgaro** [MADStudioNU/the-pulter-project#700]
Links (including DOI) are updated and should be working

**Comment by katgaro** [comment]
Update C107, "Did hunters really ride whales like horses?"; C46 and C81, "Lark Mirrors" (same title, same Curation attached to two poems).

**Comment by sergei-kalugin** [comment]
These 3 have been updated on the preview site.

@katgaro: make sure to exclude `http:` or `https:` from the `href` attribute when adding links anywhere on the site (see #605).

**Comment by katgaro** [comment]
@sergei-kalugin Thank you for reminding me! 

This first link in note 4 of C107, "Did hunters really ride whales like horses?" does not work, so I removed it. Maybe because it is linked to a PDF? Two PDF files come up in Google results when searching the title of the document, one of which was the original broken link. I tried the second, but it also does not work.

Can we update the Preview for this C107? Everything is good to be moved to the live site after that.
