### ISSUE TITLE
"Hester Pulter's DOB" Exploration: Image resizing

### ISSUE THREAD

**Issue by katgaro** [MADStudioNU/the-pulter-project#701]
Images 5-11 need to be made smaller so they are not so pixelated. A new style needs to be added for smaller images, as per @sergei-kalugin

**Comment by sergei-kalugin** [comment]
@katgaro: looks like the intrinsic size of the images is 800px width, I think they were generated as screenshots of a zoomed-in image. In order to obtain a non-pixelated image, we need to go back to the original hi-res. Could you point me to that file, please?

**Comment by katgaro** [comment]
@sergei-kalugin here is a folder of the original images: https://drive.google.com/drive/folders/1FjuYUPwn1ckSG2suh8cdJmUdMN7jyL5C?usp=sharing

There are two subfolders. "Unmodified" are the true originals. Here is a list of the relevant files:
- IMG_4907 / IMG_4909
	- image 5 under "Hester" 
	- image 6 under "James"
- IMG_4903
	- image 7 under "James Ley"
	- image 8 under "Elizabeth"
	- image 9 under "Anne"
	- images 10 and 11 in the marginal notes beside "Elizabeth"

**Comment by sergei-kalugin** [comment]
I've looked at the "source" images and they are not that hi-res. Do you guys think we can obtain the original scans or we have to work with what we have in the "unmodified" folder?

**Comment by LeahKnight** [comment]
Absolutely, my mistake; I've chucked those crappy ones and uploaded ones 3x as good.

**Comment by LeahKnight** [comment]
@katgaro Sergei and I can't locate image 11 (the closest of the close-ups on just "8"). Can you help us out?

**Comment by sergei-kalugin** [comment]
I added an alternative for image-5 just to see if this is the right direction:

![Screen Shot 2021-08-12 at 16 37 39](https://user-images.githubusercontent.com/2558705/129273462-d3120189-8491-4c73-a12f-8ec6762c374e.png)

**Comment by sergei-kalugin** [comment]
And the wider screen version:

![Screen Shot 2021-08-12 at 16 39 03](https://user-images.githubusercontent.com/2558705/129273610-0a1feadf-f45b-4264-af11-41488a572762.png)

**Comment by LeahKnight** [comment]
@sergei-kalugin , could you try it like this, but clearing away a bit of the verbiage around "1605": I worry that some folk might not locate the date at all, since it's all so messy. I'd suggest a frame that includes "Raigne of" (above) and "as baptized" (below). That will also make the figures larger, won't it--which might also help folk see the shape of the "5."

**Comment by sergei-kalugin** [comment]
Got you, @LeahKnight, will just include the line above and the line below. The figure will not become larger since its already at 100% zoom. If you wish to zoom in the image will loose some quality (become more pixelated) which could be fine, I suppose.

**Comment by sergei-kalugin** [comment]
@LeahKnight: I updated all the close-ups. What do you think?

https://pulterproject-preview-c7ga82m1pzxmbn.netlify.app/#hester-pulters-date-of-birth

**Comment by LeahKnight** [comment]
I think it looks great: thanks so very much, Sergei! I'll double-check with @katgaro that it's otherwise ready to publish.

**Comment by katgaro** [comment]
Looks great @sergei-kalugin 

We need to update the preview once more because of a minor punctuation correction and then this Exploration can be published (I'll make separate issues for both of these requests)
