### ISSUE TITLE
"Hester Pulter's DOB" Exploration: reformat the citations

### ISSUE THREAD

**Issue by sergei-kalugin** [MADStudioNU/the-pulter-project#710]

**Comment by sergei-kalugin** [comment]
@LeahKnight, please take a look: 

https://pulterproject-preview-c7ga82m1pzxmbn.netlify.app/#hester-pulters-date-of-birth

Before:
![Screen Shot 2021-08-12 at 15 04 03](https://user-images.githubusercontent.com/2558705/129266121-13f64002-aeb5-487b-ba82-c9b7f5f6d333.png)



After:
![Screen Shot 2021-08-12 at 15 40 43](https://user-images.githubusercontent.com/2558705/129266671-8c06504e-aab4-43fd-b60a-cb4389c5f07a.png)

**Comment by LeahKnight** [comment]
Excellent! Thanks, @sergei-kalugin; 

@katgaro : can you, in the relevant encoding guide, make a note about this approach to inset/block quotations, please?
