### ISSUE TITLE
New C19s: move to preview

### ISSUE THREAD

**Issue by syreeves** [MADStudioNU/the-pulter-project#727]
Hello @sergei-kalugin 

Would you be able to update the site for both c19 Bell Tolling and c19 Personified Death in Early Modern Art and Literature?

Thanks!

**Comment by sergei-kalugin** [comment]
Done!

**Comment by syreeves** [comment]
@sergei-kalugin for some reason I can't see these Curations on the preview site!

**Comment by sergei-kalugin** [comment]
@syreeves: were those new?

**Comment by sergei-kalugin** [comment]
Sorry, @syreeves, those *are*  new curations. I'll publish them in a minute.

**Comment by sergei-kalugin** [comment]
[C19 Bell Tolling](https://pulterproject-preview-c7ga82m1pzxmbn.netlify.app/poems/ee/the-welcome-1/#bell-tolling)

[C19 Personified Death in Early Modern Art and Literature](https://pulterproject-preview-c7ga82m1pzxmbn.netlify.app/poems/ee/the-welcome-1/#personified-death-in-early-modern-art-and-literature)
