### ISSUE TITLE
C19s and A19: update preview and fix link

### ISSUE THREAD

**Issue by syreeves** [MADStudioNU/the-pulter-project#736]
Hello! @sergei-kalugin 

Can you update both C19 Bell Tolling and C19 Personified Death on the preview site, as well as Poem 19?

I also can't seem to get the link to an external Curation to work on the first note in the AE for Poem 19 (Dear Death should lead to Poem 65, but instead it only scrolls down to the Curations of Poem 19). Thanks!

**Comment by sergei-kalugin** [comment]
@syreeves, FYI: https://github.com/MADStudioNU/the-pulter-project/issues/627#issuecomment-845542514

**Comment by sergei-kalugin** [comment]
@syreeves: is this what you had in mind?

https://pulterproject-preview-c7ga82m1pzxmbn.netlify.app/poems/ae/the-welcome-1/#0

**Comment by syreeves** [comment]
Ah - I must have forgotten to update our coding sheet!
<img width="717" alt="Screen Shot 2021-11-12 at 11 50 23 AM" src="https://user-images.githubusercontent.com/80483087/141504138-b1c99388-4d1d-427b-9c04-fdec01b5931d.png">

That was what we had, which was not working. I appreciate the fix!
