### ISSUE TITLE
Preview Site Update: C019 and A019

### ISSUE THREAD

**Issue by syreeves** [MADStudioNU/the-pulter-project#737]
Hello! @sergei-kalugin 

Apologies, I need just one more update on C019 Personified Death and A019. The links to Curations weren't working again, but I believe it's because I accidentally threw in a capital letter where there shouldn't have been one. Thank you!

**Comment by sergei-kalugin** [comment]
@syreeves: the compilation process of the preview site is now automatically triggered by your commits. It takes approximately 3 minutes to build the preview and publish it.

Look for the green checkmark next to the commit message — it confirms that the whole process successfully finished.

![Screen Shot 2021-11-15 at 10 32 22 AM](https://user-images.githubusercontent.com/2558705/141818951-fee399a1-3f70-48c4-b65a-47eda2eeb5dd.png)
