### ISSUE TITLE
A019, C019: Fix-up and Publish

### ISSUE THREAD

**Issue by syreeves** [MADStudioNU/the-pulter-project#739]
Hello! @sergei-kalugin 

The AE for Poem 19, as well as the Curations "Bell Tolling" and "Personified Death in Early Modern Art and Literature" for the same poem are ready to be published. Thanks!

**Comment by sergei-kalugin** [comment]
These three have been published:

- [**A019: The Welcom**](https://pulterproject.northwestern.edu/poems/ae/the-welcome-1/)
- [**C019: Bell Tolling**](https://pulterproject.northwestern.edu/poems/ae/the-welcome-1/#bell-tolling)
- [**C019: Personified Death …**](https://pulterproject.northwestern.edu/poems/ae/the-welcome-1/#personified-death-in-early-modern-art-and-literature)

There are some issues that I noticed in **C019s**:

- Links to poems/curations do not work
- The footnotes are not formatted properly
- A paragraph is misplaced

![Screen Shot 2021-11-30 at 15 48 15](https://user-images.githubusercontent.com/2558705/144133457-39d4c0b5-45f4-46fc-976d-ec522971b011.png)

**Comment by sergei-kalugin** [comment]
Fixed and live!
