### ISSUE TITLE
Update Preface and Manuscript Exploration

### ISSUE THREAD

**Issue by katgaro** [MADStudioNU/the-pulter-project#769]
Two pages need to be updated:
1: Preface page "[About Hester Pulter and The Manuscript](https://github.com/MADStudioNU/the-pulter-project/blob/develop/pulter-site/pages/about-hester-pulter-and-the-manuscript.html)"; adding a sentence with a link to the exploration
2: Exploration "[What else is in the manuscript?](https://github.com/MADStudioNU/the-pulter-project/blob/develop/pulter-site/explorations/what-else-is-in-the-manuscript.html)"; adding Wendy's corrections

@wendywall

**Comment by sergei-kalugin** [comment]
@katgaro : do these two things need to be implemented or just published?
