### ISSUE TITLE
A099b: Ready to Publish

### ISSUE THREAD

**Issue by katgaro** [MADStudioNU/the-pulter-project#772]

**Comment by katgaro** [comment]
@LeahKnight @sergei-kalugin 

What seems to have happened is that the names of the editors somehow switched on GH. I am not sure how this happened—on my end, on the files that I uploaded for A099 (Zhang) and A099b (Heffernan), everything appears where it should. I have made the correction so all should be in place for publishing A099b (Heffernan) and eventually A099 (Zhang).

Heffernan is ready to be publish, Zhang is not. Can we publish A099b without A099?

**Comment by sergei-kalugin** [comment]
@katgaro, that's exactly what I did 🤷 but somehow it was not what @LeahKnight wanted. Perhaps, she could explain here what's the status and the plan with A099 (Heffernan) and A099 (Zhang) is.

**Comment by sergei-kalugin** [comment]
@LeahKnight: should we assign AE labels (AE A, AE B, AE C...) based on the publication date? So the A099 by Megan Heffernan (the one that's ready to go) is going to be "Amplified Edition A," correct?

**Comment by sergei-kalugin** [comment]
Published!

https://pulterproject.northwestern.edu/poems/ae/mark-but-those-hogs-emblem-34/

Sorry everyone for the confusion.

**Comment by wendywall** [comment]
Thanks, Sergei. This seems right to me now. I’ll let Leah weigh in tomorrow when she’s back online.

Wendy

From: Sergei Kalugin ***@***.***>
Date: Tuesday, June 21, 2022 at 3:58 PM
To: MADStudioNU/the-pulter-project ***@***.***>
Cc: Subscribed ***@***.***>
Subject: Re: [MADStudioNU/the-pulter-project] A099b: Ready to Publish (Issue #772)

Published!

https://pulterproject.northwestern.edu/poems/ae/mark-but-those-hogs-emblem-34/

Sorry everyone for the confusion.
