### ISSUE TITLE
A045: Ready to Publish

### ISSUE THREAD

**Issue by katgaro** [MADStudioNU/the-pulter-project#778]
Sarah Ross AE

**Comment by sergei-kalugin** [comment]
https://pulterproject.northwestern.edu/poems/ae/this-was-written-in-1648-when-i-lay-in-with-my-son-john/

**Comment by wendywall** [comment]
Wonderful! Katrina, might you devise a tweet for this one?

Wendy

Wendy Wall
Co-director with Leah Knight
The Pulter Project: Poet in the Making<http://pulterproject.northwestern.edu/>
(Follow: @PulterProject)
Avalon Foundation Professor of the Humanities
Northwestern University



From: Sergei Kalugin ***@***.***>
Reply-To: MADStudioNU/the-pulter-project ***@***.***>
Date: Monday, July 18, 2022 at 10:28 AM
To: MADStudioNU/the-pulter-project ***@***.***>
Cc: Subscribed ***@***.***>
Subject: Re: [MADStudioNU/the-pulter-project] A045: Ready to Publish (Issue #778)


https://pulterproject.northwestern.edu/poems/ae/this-was-written-in-1648-when-i-lay-in-with-my-son-john/
