### ISSUE TITLE
Index Page Improvements

### ISSUE THREAD

**Issue by sergei-kalugin** [MADStudioNU/the-pulter-project#785]
Per @LeahKnight :

On the poem index page, please

- [x] ensure the comparison-tool icons beside each poem link out to a new tab;
- [x] make the icon more visible by enlarging it, brightening it, and/or moving it beside the poem’s title instead of the first line;
- [x] add a box, above the phrase “Showing 120 poems in the same order as in the manuscript”
- [x] in the box, add this text: “Below, Pulter’s 120 poems appear in the order in which they appear in the manuscript. Select a tag to filter the poems. Or try our comparison tool to see different versions of the poems side by side.”
- [x] link the phrase “comparison tool” to Poem 1 in the comparison tool
- [x] make blurb images consistent ratio-wise
- [x] try boxing the tags
- [x] update tags styles
- [x] improve Index Page blurb copy
- [x] move commas out of the CSS or get rid of them

**Comment by sergei-kalugin** [comment]
Links to VM in the index now open in new tab.

**Comment by sergei-kalugin** [comment]
@LeahKnight: I made some changes to the index page. Can you take a look and let me know if they make sense? Instead of displaying a box initially, I hid the contents in another lightbox that can be triggered by clicking on the "i" next to the "POEMS" label. I would also appreciate if you check the copy of the message that's housed in that lightbox at the moment. Thank you!

**Comment by wendywall** [comment]
Hi – how can I see the alterations to the index poem page?

Wendy

From: Sergei Kalugin ***@***.***>
Date: Friday, September 22, 2023 at 4:23 PM
To: MADStudioNU/the-pulter-project ***@***.***>
Cc: Subscribed ***@***.***>
Subject: Re: [MADStudioNU/the-pulter-project] Index Page Improvements (Issue #785)

Closed #785<https://urldefense.com/v3/__https:/github.com/MADStudioNU/the-pulter-project/issues/785__;!!Dq0X2DkFhyF93HkjWTBQKhk!S757kRf7J-yu8OJddk9OU0HsPjX_LoIX20pDoonMqiN9KFeEf-dGBvppWYRPRg5fDavHNcNA0MGmewK3G_oWHddeqvlEn8I$> as completed.

**Comment by sergei-kalugin** [comment]
@wendywall: this issue is just regarding an "i" next POEMS. You can see the implementation on the preview site: https://pulterproject-preview-c7ga82m1pzxmbn.netlify.app/#poems

The work that's being done for the curations+explorations index is tracked here: #886
