### ISSUE TITLE
Update "The Project" page

### ISSUE THREAD

**Issue by KnightLeah** [MADStudioNU/the-pulter-project#787]
@sergei-kalugin

**Comment by sergei-kalugin** [comment]
@KnightLeah, by "update" you mean "publish new stuff to the production?"

**Comment by KnightLeah** [comment]
@sergei-kalugin:  good point; how about "publish to preview," so I can proofread it first--how do I ask for that GitSpeak?

**Comment by sergei-kalugin** [comment]
OK, the preview site should be updated automatically upon a push to the repo (with a 2-3 minute delay). SO, the change should be reflected on the site. Once you confirm that everything looks good, I'll publish the new version.

**Comment by KnightLeah** [comment]
@sergei-kalugin Hmm ... I don't see my changes. I cleared my cache and everything. Ideas?
