### ISSUE TITLE
Poem 99 AEs: Update

### ISSUE THREAD

**Issue by katgaro** [MADStudioNU/the-pulter-project#789]
"Amplified Edition A"/"Amplified Edition B" added to AEs

@sergei-kalugin Are these changes something that should be reflected in the index/search results as well?

**Comment by sergei-kalugin** [comment]
Yes, I will need to update the manifest. Just to clarify, two new AEs have been added and ready to be published to production?

**Comment by KnightLeah** [comment]
@sergei-kalugin Actually, it's just the distinguishing labels of "Amplified Edition A" and "B" that has been added to the extant AEs for Poem 99. Katrina wanted to be sure that labelling is reflected in the index as well (as for Poem 10, say).

**Comment by katgaro** [comment]
@sergei-kalugin @KnightLeah Leah is correct! The distinguishing labels were added to both but, as of now, only Amplified Edition A of Poem 99 is published and needs to be updated. Edition B is not yet ready to publish.

Thank you
