### ISSUE TITLE
Broadfield image on "The Poet" Page

### ISSUE THREAD

**Issue by katgaro** [MADStudioNU/the-pulter-project#793]
@sergei-kalugin is it possible to centre the image of Pulter's house?

Here is a link to the page in question: https://pulterproject.northwestern.edu/about-hester-pulter-and-the-manuscript.html

**Comment by sergei-kalugin** [comment]
Yes, definitely possible. Not sure if it looks better aligned centrally vs to the left though.

**Comment by LeahKnight** [comment]
It looks fine as is--I'll close this. Thanks, both!
