### ISSUE TITLE
Poem 116: add “Charles I" to keywords/tags in index

### ISSUE THREAD

**Issue by LeahKnight** [MADStudioNU/the-pulter-project#797]
@sergei-kalugin

**Comment by sergei-kalugin** [comment]
@LeahKnight, just double-checking: there's already `Charles II` specified for Poem 116. I want to make sure it's not a typo, since it's the only occurrence on `Charles II` in the entire index.

In other words, do both `Charles I` and `Charles II` need to appear under Poem 116?

**Comment by LeahKnight** [comment]
Excellent eye, as usual, @sergei-kalugin ! And yes, we want both Charles I and Charles II. (The latter doesn't get much of a look-in with HP, you're right; he turned out quite a prat, is probably why.)
