### ISSUE TITLE
Update to Production site EEs and AEs

### ISSUE THREAD

**Issue by katgaro** [MADStudioNU/the-pulter-project#801]
Links in all of the following have been corrected/added, so the production site needs updating:
A034-38
A043
A044
A046
A048
A050
A051
A053
A054

E041
E043
E051
E054
E055

**Comment by katgaro** [comment]
More poems to add to the list:
E056
E088
E097

A059
A061
A063
A065
A066
A068
A070-72
A076
A079
A088
A089
A098
A103-105
A114

**Comment by sergei-kalugin** [comment]
@katgaro, thank you for the updates. There are a few syntax errors that fail the build. Would you be able to revise your work? No worries if not, someone from our team will take care of this soon-ish.

**Comment by sergei-kalugin** [comment]
It looks like the culprit is
> `<ref="pp-poem-ref" corresp="51">[POEM TITLE]</ref>`

which should be

> `<ref type="pp-poem-ref" corresp="51">[POEM TITLE]</ref>`

There are a bunch of there throughout the corpus.

**Comment by katgaro** [comment]
@sergei-kalugin I will absolutely review the poems I worked on and fix these errors. Thank you for pointing out the issue! I'll keep everyone updated

**Comment by katgaro** [comment]
@sergei-kalugin I think the issue is resolved? I've gone through all the corrections I've made and fixed the errors. If there is any outstanding problem that I can address, please let me know

**Comment by sergei-kalugin** [comment]
Looks like it's passing again. Thank you so much, @katgaro! I'm going to push all the changes live shortly!

**Comment by sergei-kalugin** [comment]
Published!
