### ISSUE TITLE
Change name of Scholarship Page

### ISSUE THREAD

**Issue by syreeves** [MADStudioNU/the-pulter-project#802]
Hello @sergei-kalugin 

We are looking to rename the Scholarship page to "Resources", so that it appears as such in both the URL and home page drop-down menu.

Thanks!

**Comment by sergei-kalugin** [comment]
The preview has been updated. Sorry it took so long to respond to this.

**Comment by LeahKnight** [comment]
@sergei-kalugin This looks good in preview, Sergei--please move to the production site (AKA publish). Thanks!

**Comment by sergei-kalugin** [comment]
https://pulterproject.northwestern.edu/resources.html
