### ISSUE TITLE
HTML Formatting: Updating exploration "Rereading Pulter's Confinement..." 

### ISSUE THREAD

**Issue by syreeves** [MADStudioNU/the-pulter-project#810]
Exploration "Rereading Pulter..." needs the following updates:
- [x] Citation title and student response to be centred (Why Must I Thus Forever Be Confined, followed by Sam Grady's response.)
- [x] Quotation "box" to be removed.
- [x] Poem lines to be converted to "Cormorant Garamond" font.
- [x] Student responses to be italicized and indented as a block.

**Comment by sergei-kalugin** [comment]
@LeahKnight: I've massaged this one a bit. Please let me know if it looks good for publishing.

https://pulterproject-preview-c7ga82m1pzxmbn.netlify.app/#rereading-pulters-confinement-in-the-pandemic

**Comment by LeahKnight** [comment]
It looks fabulous! Thanks @sergei-kalugin Publish at will!
