### ISSUE TITLE
Poem 5: 1st line displays incorrectly in index

### ISSUE THREAD

**Issue by LeahKnight** [MADStudioNU/the-pulter-project#818]
Poem's first word is "Night's" but displays as "Night"
https://pulterproject.northwestern.edu/#poems

**Comment by LeahKnight** [comment]
@sergei-kalugin I still see this problem in the index--are you sure it's been fixed?

**Comment by sergei-kalugin** [comment]
Fixed in preview but not published yet

**Comment by LeahKnight** [comment]
Published now, I see--thanks!
