### ISSUE TITLE
Add support for headnote images 

### ISSUE THREAD

**Issue by wendywall** [MADStudioNU/the-pulter-project#830]
For A080 @sergei-kalugin @

**Comment by sergei-kalugin** [comment]
@meclifton, the headnote image is not encoded yet, right?

**Comment by meclifton** [comment]
@sergei-kalugin Correct

**Comment by sergei-kalugin** [comment]
The image has been added: https://pulterproject-preview-c7ga82m1pzxmbn.netlify.app/poems/ae/the-stately-unicorn-emblem-14/
