### ISSUE TITLE
A008: missing link

### ISSUE THREAD

**Issue by wendywall** [MADStudioNU/the-pulter-project#833]
A008: Add link to reference to Poem 15 in second paragraph of Ross's headnote:  @sergei-kalugin

**Comment by sergei-kalugin** [comment]
It is the second mention of Poem 15, but I still converted it to a stylized link.

https://pulterproject-preview-c7ga82m1pzxmbn.netlify.app/poems/ae/on-that-unparalleled-prince-charles-the-first-his-horrid-murder/

**Comment by meclifton** [comment]
Sorry, I missed this one!
