### ISSUE TITLE
Add support for internal TPP links to AEs

### ISSUE THREAD

**Issue by meclifton** [MADStudioNU/the-pulter-project#851]
@sergei-kalugin 
Currently in order to keep TPP formatting for poem links (see the image attached for reference), it can only direct to EEs. It would be good to have an option to encode poem links to AEs as well that keep similar formatting. This could be used in EE/AEs, Curations or Explorations, and so should be able to work in both XML and HTML files.

At the moment the only page that requires this is A111.

![image](https://github.com/MADStudioNU/the-pulter-project/assets/60953623/4b9653ee-e760-4d3d-90d4-87171abe371d)

**Comment by sergei-kalugin** [comment]
This has been added. Here's how to encode links to AEs:

`<ref type="pp-poem-ref" corresp="67" target="ae">Mighty Nimrod (Emblem 1)</ref>`
