### ISSUE TITLE
Thomas Ward: Add bio info

### ISSUE THREAD

**Issue by meclifton** [MADStudioNU/the-pulter-project#854]
@sergei-kalugin 
Thomas Ward, United States Naval Academy. He provided a bio link at https://usna.academia.edu/ThomasWard. He wrote A083.

**Comment by sergei-kalugin** [comment]
https://pulterproject-preview-c7ga82m1pzxmbn.netlify.app/poems/ae/the-piper-of-hamelin-emblem-17/
