### ISSUE TITLE
Encode A040 (Hatton) and C040 (Hatton)

### ISSUE THREAD

**Issue by wendywall** [MADStudioNU/the-pulter-project#857]
Please encode A040 and two curations: C040.  @meclifton

**Comment by sergei-kalugin** [comment]
@wendywall, could you please provide the name of the collaborator as well (for clarity and consistency)

**Comment by wendywall** [comment]
OK, I'm trying here. The editor is Nikolina Hatton. If you need more, I'll have to get Leah to help

**Comment by sergei-kalugin** [comment]
That's perfect, thank you!

**Comment by meclifton** [comment]
On it--but I'll need access to A040 and C040(s) in order to encode them

**Comment by sergei-kalugin** [comment]
@LeahKnight: could you share with us a link to the source Google Doc (I assume)?

**Comment by meclifton** [comment]
Got them myself directly. For posterity, here's [A040](https://docs.google.com/document/d/1_ajW8FY4HcQ9GjRtUFthjypCYEj5O8lNJ425Stnvy6s/edit?usp=sharing), [C040a](https://docs.google.com/document/d/1kYd4ACR2lvHjOhvMhcnpd3gP31JkltchCqh3BYEDsW8/edit?usp=sharing), and [C040b](https://docs.google.com/document/d/1kYhZzroOnMlKKX1Pha7CAiOf3AnMCLrAAmEscvcG7ME/edit?usp=sharing).
