### ISSUE TITLE
C064s: fix `title`s and tons of apostrophes

### ISSUE THREAD

**Issue by KnightLeah** [MADStudioNU/the-pulter-project#865]
@sergei-kalugin A search for "Sandys" turns up, in the search results, only PART of the title of Elizabeth Sauer's Curation on that figure for Poem 64.  Other Curations see their whole titles displayed.

**Comment by sergei-kalugin** [comment]
Thank you, @LeahKnight!

The issue is with all "Pulter Reads..." curations. I'll apply the fix shortly.
