### ISSUE TITLE
Publish new poster images for Poem 38

### ISSUE THREAD

**Issue by meclifton** [MADStudioNU/the-pulter-project#867]
@sergei-kalugin 
The poster image should be updated to the image found at [this link](https://luna.folger.edu/luna/servlet/detail/FOLGERCM1~6~6~1136738~182754:The-Historical-Antiquities-of-Hertf%3Fsort%3Dcall_number%252Cmpsortorder1%252Ccd_title%252Cimprint?qvq=q:Chauncy%20antiquities%20hertfordshire;sort:call_number%2Cmpsortorder1%2Ccd_title%2Cimprint;lc:FOLGERCM1~6~6&mi=2&trs=46).

**Comment by sergei-kalugin** [comment]
@meclifton, the poster images live in their own repository: 

https://github.com/MADStudioNU/the-pulter-project-posters

Would you be able to add the new image there?

**Comment by meclifton** [comment]
@sergei-kalugin can you give me write access to the repository? Also I can add the "og" image but is there a guide/person to talk to for me to make the dark/light/etc versions or should I leave that to you?

**Comment by sergei-kalugin** [comment]
https://pulterproject.northwestern.edu/poems/ee/to-my-dear-jane-margaret-and-penelope-pulter/
