### ISSUE TITLE
Publish A040 & C040s to production

### ISSUE THREAD

**Issue by meclifton** [MADStudioNU/the-pulter-project#871]
@sergei-kalugin This includes A040 from the pulter_040.xml file, and then `c40-pulters-psalmic-intertexts.html` as well as `c40-metaphors-of-violence-in-devotional-poetry.html`

**Comment by sergei-kalugin** [comment]
https://pulterproject.northwestern.edu/poems/ae/my-soul-why-art-thou-full-of-trouble/
