### ISSUE TITLE
Update attribution for P38 poster

### ISSUE THREAD

**Issue by meclifton** [MADStudioNU/the-pulter-project#877]
@sergei-kalugin The attribution caption for the poster image isn't updated yet. I'm happy to do this, just not sure which file this is housed in. Could you let me know?

**Comment by sergei-kalugin** [comment]
https://github.com/MADStudioNU/the-pulter-project/blob/122c35c70ed40d1dd14ef68b7810f52bb01dfedc/pulter-site/xslt/poems.xsl#L2183
