### ISSUE TITLE
Add family tree demo

### ISSUE THREAD

**Issue by sergei-kalugin** [MADStudioNU/the-pulter-project#884]
- [x] add a "collapsible" to hide the tree
- [x] customize HP's node
- [x] customize HP's sidebar styling
- [x] mobile styles?
- [x] what to to with the image lightbox in the side panel?
- [x] prevent auto emoji conversion of the "cross" Unicode character 
- [x] change selection color

**Comment by wendywall** [comment]
Hi, Sergei,

I hope that you had a lovely vacation in the mountains.

I’m writing to follow up with you about our meeting regarding the family tree prototype and progress on the new index page. Would it be best to schedule a Zoom with Leah and me to get an update before the term gets hectic?

Wendy

From: Sergei Kalugin ***@***.***>
Date: Thursday, August 24, 2023 at 4:58 PM
To: MADStudioNU/the-pulter-project ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [MADStudioNU/the-pulter-project] Add family tree demo (Issue #884)

**Comment by sergei-kalugin** [comment]
A demo has been added.

https://pulterproject-preview-c7ga82m1pzxmbn.netlify.app/about-hester-pulter-and-the-manuscript
