### ISSUE TITLE
Add Curations/Explorations index to the site (first iteration)

### ISSUE THREAD

**Issue by sergei-kalugin** [MADStudioNU/the-pulter-project#886]
<img width="702" alt="Screenshot 2023-09-22 at 4 32 52 PM" src="https://github.com/MADStudioNU/the-pulter-project/assets/2558705/5fe980d5-325e-4527-b7cb-e55559ca51be">

**Comment by sergei-kalugin** [comment]
@LeahKnight : could you please remind me of a word we're using to refer to both Curations and Explorations?

**Comment by wendywall** [comment]
Connections. I’ll let lk confirm

This one was sent from my iPhone, for better or worse...


On Sep 27, 2023, at 4:35 PM, Sergei Kalugin ***@***.***> wrote:

﻿

@LeahKnight<https://urldefense.com/v3/__https://github.com/LeahKnight__;!!Dq0X2DkFhyF93HkjWTBQKhk!UXkoeJA7WSY8QvlBF9z9NpFf1UaMimfLbjQ3Nie9Q2U9Odrq28ES63kvN5un5wqF6X08CMKyQmzbs4z4jt6JohEqa-SAb_I$> : could you please remind me of a word we're using to refer to both Curations and Explorations?

**Comment by KnightLeah** [comment]
> @LeahKnight : could you please remind me of a word we're using to refer to both Curations and Explorations?

@sergei-kalugin Confirmed: "Connections" it is.

**Comment by sergei-kalugin** [comment]
https://pulterproject-preview-c7ga82m1pzxmbn.netlify.app/#connections
