### ISSUE TITLE
Update A119 in preview

### ISSUE THREAD

**Issue by KnightLeah** [MADStudioNU/the-pulter-project#892]
@sergei-kalugin would you please add the following profile links to A119? 

Anna-Rose Shack
https://www.uva.nl/en/profile/s/h/a.k.shack/a.k.shack.html
 
Kristine Johanson
https://www.uva.nl/en/profile/j/o/k.a.johanson/k.a.johanson.html

**Comment by sergei-kalugin** [comment]
https://pulterproject-preview-c7ga82m1pzxmbn.netlify.app/poems/ae/an-old-man-a-stripling-and-an-ass-emblem-54/
