### ISSUE TITLE
Publish A078

### ISSUE THREAD

**Issue by syreeves** [MADStudioNU/the-pulter-project#902]
Hi @sergei-kalugin , A078 is ready for publication! Thanks

**Comment by wendywall** [comment]
﻿Thanks, Sydney, for your work on this poem, and happy new year to all!

Sydney, I think that Leah has queried you about your availability for encoding two more poems that are almost ready.

Best,
Wendy

From: Sydney ***@***.***>
Date: Wednesday, January 3, 2024 at 8:21 AM
To: MADStudioNU/the-pulter-project ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [MADStudioNU/the-pulter-project] Publish A078 (Issue #902)

Hi @sergei-kalugin<https://urldefense.com/v3/__https:/github.com/sergei-kalugin__;!!Dq0X2DkFhyF93HkjWTBQKhk!XIrZKgVyasQuBLo7pjb7emUUAxhkMZGjQBbmH47GlmfINJl78vWXK6OFQEabmSl_17hoJusk8KC0bpaUdmaONt-Xa0yo-Ps$> , A078 is ready for publication! Thanks

**Comment by sergei-kalugin** [comment]
https://pulterproject.northwestern.edu/poems/ae/this-vast-leviathan-emblem-12/
