### ISSUE TITLE
Move C115 x 3 to preview

### ISSUE THREAD

**Issue by KnightLeah** [MADStudioNU/the-pulter-project#913]
@sergei-kalugin Please move the 3 Curations for Poem 115 to the preview site for proofreading.

**Comment by sergei-kalugin** [comment]
https://pulterproject-preview-c7ga82m1pzxmbn.netlify.app/poems/ae/phalaris-and-the-brazen-bull-emblem-50/#ae

@KnightLeah: please see #914
