### ISSUE TITLE
C115s (Koch): add keywords

### ISSUE THREAD

**Issue by sergei-kalugin** [MADStudioNU/the-pulter-project#914]
- [x] C115a (_Phalaris and Perillus in Early Modern Print_)
- [x] C115b (_Procrustes, Sciron, Termerus, and Sinis in Early Modern Print_)
- [ ] C115c (_Pulter and Jamaica_)

**Comment by wendywall** [comment]
@sergei-kalugin. The keywords for each Curation are found on the metadata sheet, Curations tab, column K
 https://docs.google.com/spreadsheets/d/1zv-dZ8TMdGD13u66NhCAqDNIvcUKtS8XfPKfbE4Ulvw/edit#gid=1863055128
