### ISSUE TITLE
Poem A109a: Move to Preview

### ISSUE THREAD

**Issue by ashleycole26** [MADStudioNU/the-pulter-project#915]
- [x] fix errors (@ashleycole26)
- [ ] publish to preview (@sergei-kalugin)

**Comment by sergei-kalugin** [comment]
A109a has a bunch of syntax issues. Will update everyone over email.

**Comment by sergei-kalugin** [comment]
Reverting 15b5955d to build and publish #916.

**Comment by ashleycole26** [comment]
@sergei-kalugin ok for preview now?

**Comment by sergei-kalugin** [comment]
Looks valid now!

https://pulterproject-preview-c7ga82m1pzxmbn.netlify.app/poems/ae/the-brahman-emblem-44/#ae
