### ISSUE TITLE
A069 Ready to Publish

### ISSUE THREAD

**Issue by syreeves** [MADStudioNU/the-pulter-project#916]
@sergei-kalugin thank you Sergei! @LeahKnight

**Comment by sergei-kalugin** [comment]
Quick checklist before publishing:
- [ ] This AE does not have an _Editorial Note_, correct?
- [ ] Are we ok with an inconsistent usage of hyphens and en dashes where we would normally put an em dash without space before and after?

**Comment by sergei-kalugin** [comment]
Update: I standardized the dashes. The only remaining question is the empty _Editorial Note_.

**Comment by syreeves** [comment]
Hi Sergei - I don't have an editorial note in the Google doc provided, unless I'm completely missing it! Reread it a few times to check. Leah or Wendy may have more info. Thank you for the em-dash standardization! For some reason I can't get em-dashes to work on my pc at the moment, just standard dashes.

**Comment by syreeves** [comment]
Editorial note is up, this is now ready for publishing!

**Comment by sergei-kalugin** [comment]
https://pulterproject.northwestern.edu/poems/ae/heliotropians-emblem-3/
