### ISSUE TITLE
C105 (Sperry): finalize metadata

### ISSUE THREAD

**Issue by sergei-kalugin** [MADStudioNU/the-pulter-project#925]
- [x] decide on the title _Resurrections at Cairo_ (in HTML) vs _Grand Caire_ (in Google Spreadsheets)
- [x] [add keywords](https://docs.google.com/spreadsheets/d/1zv-dZ8TMdGD13u66NhCAqDNIvcUKtS8XfPKfbE4Ulvw/edit#gid=1863055128&range=K239)

**Comment by wendywall** [comment]
@sergei-kalugin   I added the keywords for the curation in column K of the curation metadata sheet
