### ISSUE TITLE
C092s (Newcombe): add keywords

### ISSUE THREAD

**Issue by sergei-kalugin** [MADStudioNU/the-pulter-project#940]
https://docs.google.com/spreadsheets/d/1zv-dZ8TMdGD13u66NhCAqDNIvcUKtS8XfPKfbE4Ulvw/edit#gid=1863055128&range=K215:K217

- [x] add keywords to the metadata sheet (@wendywall )
- [x] add keywords to the manifest (@sergei-kalugin)

**Comment by wendywall** [comment]
added keywords for cuations to metadata sheet @sergei-kalugin
