### ISSUE TITLE
Publish to Preview: A092 + Curations 

### ISSUE THREAD

**Issue by ashleycole26** [MADStudioNU/the-pulter-project#946]

**Comment by sergei-kalugin** [comment]
Nice, @ashleycole26!

Just FYI: once a poem/connection has been published to preview, all further changes should be reflected on the preview site within 5 minutes. The way to know it for sure is to check for a green checkmark next to the commit.

![Screen Shot 2024-03-12 at 5 11 07 PM](https://github.com/MADStudioNU/the-pulter-project/assets/2558705/1aa35345-6b54-4fbf-86f6-e1945789bd9b)

**Comment by ashleycole26** [comment]
Hi,

Oh ok, thank you I wasn't aware of this. Also, everything we fixed
yesterday looks good for A092 and Curations except for the bullet point
that still appears in the indented line of the block citation in Shipwrecks
and Civil War. Not sure how to fix this. Let me know if you have any ideas.

Best,
Ashley

**Comment by sergei-kalugin** [comment]
I will take a look at the stubborn line, @ashleycole26.

**Comment by ashleycole26** [comment]
thank you!
