### ISSUE TITLE
c105-resurrections-at-cairo: fixes

### ISSUE THREAD

**Issue by sergei-kalugin** [MADStudioNU/the-pulter-project#952]
- [x] The footnote refs appear to be incorrect
- [x] needs to go though the [Preflight Check List](https://github.com/MADStudioNU/the-pulter-project/wiki/Pre%E2%80%90Flight-Check-List)

**Comment by ashleycole26** [comment]
What exactly are you referring to?

**Comment by ashleycole26** [comment]
Is this something for me to fix? @sergei-kalugin

**Comment by sergei-kalugin** [comment]
Yes, please make sure the links to and from the footnotes work properly and check that numerical ranges have en dashes as separators.

**Comment by ashleycole26** [comment]
@sergei-kalugin Do you still need me to fix this?

**Comment by sergei-kalugin** [comment]
No, that's been taken care of. Thanks!
