### ISSUE TITLE
Publish A015, C015, and two explorations to Preview

### ISSUE THREAD

**Issue by ashleycole26** [MADStudioNU/the-pulter-project#993]
The explorations: women-writers-english-revolution.html & pulter-and-political-revolution.html

---

- [x] Apply fixes and corrections: use exploration template for explorations
- [x] Publish to preview

**Comment by sergei-kalugin** [comment]
**A015**
https://pulterproject-preview-c7ga82m1pzxmbn.netlify.app/poems/ae/let-none-sigh-more-for-lucas-or-for-lisle-on-the-same-2/

**C015**
https://pulterproject-preview-c7ga82m1pzxmbn.netlify.app/poems/ae/let-none-sigh-more-for-lucas-or-for-lisle-on-the-same-2/#arthur-first-baron-capel

_**Pulter and Political Revolution**_
https://pulterproject-preview-c7ga82m1pzxmbn.netlify.app/#pulter-and-political-revolution

_**Women Writers and the English Revolution**_
https://pulterproject-preview-c7ga82m1pzxmbn.netlify.app/#women-writers-and-the-english-revolution
